import React, { ChangeEvent, useEffect, useMemo, useState } from 'react'
import Plot from 'react-plotly.js'

type Any = Record<string, any>
type Method = { id: string, name: string, category: string, description: string, minimum: string }
function useMultivariateStyles() { useEffect(() => { const link = document.createElement('link'); link.id = 'multivariate-styles'; link.rel = 'stylesheet'; link.href = '/multivariate.css'; document.head.appendChild(link); return () => link.remove() }, []) }

const METHODS: Method[] = [
  {id:'regression',name:'Multiple Regression',category:'Regression',description:'Explain or predict one continuous outcome.',minimum:'1 outcome + 1 predictor'},
  {id:'manova',name:'MANOVA',category:'Hypothesis testing',description:'Compare several outcomes between groups.',minimum:'2 outcomes + group'},
  {id:'canonical',name:'Canonical Correlation',category:'Relationships',description:'Relate two sets of numeric variables.',minimum:'2 variables per set'},
  {id:'pca',name:'Principal Component Analysis',category:'Dimension reduction',description:'Summarise correlated numeric variables.',minimum:'2 numeric variables'},
  {id:'factor',name:'Factor Analysis',category:'Dimension reduction',description:'Find latent factors behind variables.',minimum:'3 numeric variables'},
  {id:'cluster',name:'Cluster Analysis',category:'Clustering',description:'Discover naturally similar observations.',minimum:'2 numeric variables'},
  {id:'discriminant',name:'Discriminant Analysis',category:'Classification',description:'Classify known groups using predictors.',minimum:'class + predictors'},
  {id:'correspondence',name:'Correspondence Analysis',category:'Categorical data',description:'Explore association between two categories.',minimum:'2 categorical variables'},
  {id:'ica',name:'Independent Component Analysis',category:'Dimension reduction',description:'Separate independent signals/components.',minimum:'2 numeric variables'},
  {id:'pls',name:'Partial Least Squares',category:'Prediction',description:'Predict outcomes with correlated features.',minimum:'X block + Y block'},
  {id:'mds',name:'Multidimensional Scaling',category:'Similarity / distance',description:'Map distances into two dimensions.',minimum:'2 numeric variables'}]
const api = async (url: string, init?: RequestInit) => { const r = await fetch(url, init); const body = await r.json(); if (!r.ok) throw new Error(body.error || 'Request failed'); return body }
const numericTypes = ['numeric','ordinal','binary']
const categoricalTypes = ['categorical','ordinal','binary']
const download = (rows: Any[], filename: string) => { const cols = [...new Set(rows.flatMap(r => Object.keys(r)))]; const esc=(v:any)=>`"${String(v ?? '').replace(/"/g,'""')}"`; const csv=[cols.join(','),...rows.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=filename;a.click();URL.revokeObjectURL(a.href) }

export default function MultivariateStatistics() { useMultivariateStyles();
  const [dataset, setDataset] = useState<Any | null>(null), [preview, setPreview] = useState<Any | null>(null), [methodId, setMethodId] = useState('pca'), [roles, setRoles] = useState<Any>({})
  const [typeMap, setTypeMap] = useState<Any>({}), [selected, setSelected] = useState<string[]>([]), [setA, setSetA] = useState<string[]>([]), [setB, setSetB] = useState<string[]>([])
  const [result, setResult] = useState<Any | null>(null), [check, setCheck] = useState<Any | null>(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState('Upload a dataset to begin.')
  const method = METHODS.find(m=>m.id===methodId)!
  const vars:Any[] = dataset?.profile?.variables || []
  const typeOf=(v:Any)=>typeMap[v.column] || v.detected_type
  const numeric=vars.filter(v=>numericTypes.includes(typeOf(v))).map(v=>v.column)
  const categorical=vars.filter(v=>categoricalTypes.includes(typeOf(v))).map(v=>v.column)
  useEffect(()=>{ if(!dataset) return; api(`/multivariate-api/api/datasets/${dataset.dataset.id}/preview`).then(setPreview).catch(()=>setPreview(null)) },[dataset])
  const config = useMemo(() => {
    const v = selected
    if(methodId==='regression') return {dependent_variable:roles.outcome,independent_variables:v.filter(x=>x!==roles.outcome)}
    if(methodId==='manova') return {dependent_variables:v,grouping_variable:roles.group}
    if(methodId==='canonical') return {set_a:setA,set_b:setB}
    if(methodId==='discriminant') return {class_variable:roles.group,predictors:v}
    if(methodId==='correspondence') return {row_variable:roles.row,column_variable:roles.column}
    if(methodId==='pls') return {x_variables:setA,y_variables:setB}
    if(methodId==='cluster') return {variables:v,algorithm:roles.algorithm || 'kmeans',n_clusters:Number(roles.clusters || 3),scale:true}
    if(methodId==='factor') return {variables:v,n_factors:Number(roles.factors || 2)}
    if(methodId==='ica') return {variables:v,n_components:Number(roles.components || 2)}
    return {variables:v}
  },[methodId,selected,setA,setB,roles])
  const chooseMethod=(id:string)=>{ setMethodId(id);setResult(null);setCheck(null);setNotice('Configure variable roles, then check suitability before running.') }
  const toggle=(name:string,setter:React.Dispatch<React.SetStateAction<string[]>>)=>setter(old=>old.includes(name)?old.filter(x=>x!==name):[...old,name])
  async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setNotice(`Inspecting ${file.name}â€¦`);try{const f=new FormData();f.append('file',file);const body=await api('/multivariate-api/api/datasets',{method:'POST',body:f});const nums=body.profile.buckets.numeric;const cats=body.profile.buckets.categorical_like;setDataset(body);setPreview(null);setTypeMap({});setSelected(nums.slice(0,Math.min(5,nums.length)));setSetA(nums.slice(0,2));setSetB(nums.slice(2,4));setRoles({outcome:nums[0]||'',group:cats[0]||'',row:cats[0]||'',column:cats[1]||'',algorithm:'kmeans',clusters:3,factors:2,components:2});setNotice('Dataset ready. Inspect the preview, then assign explicit variable roles.')}catch(err:any){setNotice(err.message)}finally{setBusy(false)}}
  async function suitability(){if(!dataset)return;setBusy(true);setNotice('Checking data requirementsâ€¦');try{const body=await api(`/multivariate-api/api/analyses/${methodId}/validate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset_id:dataset.dataset.id,config,type_map:typeMap})});setCheck(body);setNotice(body.applicable?'Ready to run. Review the checks below.':'Adjust the highlighted selection before running.')}catch(err:any){setNotice(err.message)}finally{setBusy(false)}}
  async function run(){if(!dataset)return;setBusy(true);setResult(null);setNotice('Running analysis and preparing resultsâ€¦');try{const body=await api(`/multivariate-api/api/analyses/${methodId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset_id:dataset.dataset.id,config,type_map:typeMap})});setResult(body);setCheck({applicable:body.applicable,preconditions:body.preconditions,assumptions:body.assumptions,errors:body.errors,warnings:body.warnings});setNotice(body.applicable?'Analysis complete.':'Analysis was stopped safely; resolve the failed checks.')}catch(err:any){setNotice(err.message)}finally{setBusy(false)}}
  return <main><aside><div className="brand">MULTIVARIATE<span>ANALYTICS STUDIO</span></div><label className="upload">Upload CSV or Excel<input type="file" accept=".csv,.xls,.xlsx" onChange={upload}/></label><p className="sidebar-note">{dataset ? `${dataset.dataset.filename} Â· ${dataset.profile.dimensions.rows.toLocaleString()} rows`:'No dataset loaded'}</p><div className="nav-title">CHOOSE AN ANALYSIS</div>{METHODS.map(m=><button key={m.id} className={'nav '+(m.id===methodId?'active':'')} onClick={()=>chooseMethod(m.id)}><span>{m.name}</span><small>{m.category}</small></button>)}</aside>
    <section className="content"><header><div><p className="eyebrow">GUIDED, DATA-FIRST ANALYSIS</p><h1>{dataset ? method.name : 'Welcome'}</h1><p className="subtitle">{dataset ? method.description : 'Upload data once; the studio helps choose, validate, and explain each analysis.'}</p></div><div className={'notice '+(notice.includes('stopped')||notice.includes('Adjust')?'warning':'')}>{busy?<i/>:null}{notice}</div></header>
    {!dataset?<Welcome/>:<><div className="stepper"><span className="done">1. Upload</span><span className="done">2. Inspect</span><span className="current">3. Configure</span><span>4. Check</span><span>5. Results</span></div><Overview dataset={dataset as Any}/><DatasetPreview preview={preview}/><div className="workspace"><article className="configuration"><div className="section-head"><div><p className="eyebrow">STEP 3</p><h2>Assign variable roles</h2></div><span className="minimum">Needs: {method.minimum}</span></div><p className="hint">Choose variables based on your research question. The system does not assume a target, group, or predictor for you.</p><Configurator method={methodId} numeric={numeric} categorical={categorical} allVariables={vars.map(v=>v.column)} selected={selected} setSelected={setSelected} setA={setA} setB={setB} setSetA={setSetA} setSetB={setSetB} roles={roles} setRoles={setRoles} toggle={toggle}/><div className="actions"><button className="secondary" disabled={busy} onClick={suitability}>Check suitability</button><button className="run" disabled={busy} onClick={run}>{busy?'Workingâ€¦':'Run analysis'}</button></div></article><VariableExplorer vars={vars} typeOf={typeOf} typeMap={typeMap} setTypeMap={setTypeMap}/></div><CheckPanel check={check}/><Recommendations data={dataset as Any} choose={chooseMethod}/>{result&&<Results result={result as Any}/>}</>}</section></main>
}
function Welcome(){return <div className="empty"><div className="empty-icon">â†¥</div><h2>Upload a CSV, XLS, or XLSX dataset</h2><p>We will inspect data quality, detect variable types, and show only analyses that fit your data. You always choose what to run.</p><div className="welcome-steps"><span>1. Upload</span><span>2. Choose an analysis</span><span>3. Select variables</span><span>4. Review checks</span></div></div>}
function Overview({dataset}:{dataset:Any}){const p=dataset.profile;return <><div className="cards"><Card label="Rows" value={p.dimensions.rows}/><Card label="Columns" value={p.dimensions.columns}/><Card label="Numeric" value={p.variable_counts.numeric}/><Card label="Missing cells" value={p.missing.total_missing}/></div>{(p.duplicate_rows||p.constant_columns.length||Object.keys(p.outliers).length)&&<div className="quality"><b>Data quality note</b>{p.duplicate_rows>0&&<span>{p.duplicate_rows} duplicate row(s)</span>}{p.constant_columns.length>0&&<span>Constant: {p.constant_columns.join(', ')}</span>}{Object.keys(p.outliers).length>0&&<span>Potential outliers in {Object.keys(p.outliers).length} variable(s)</span>}<small>Nothing is removed automatically. Review and decide before drawing conclusions.</small></div>}</>}
const Card=({label,value}:{label:string,value:any})=><div className="card"><small>{label}</small><strong>{Number(value).toLocaleString()}</strong></div>
function DatasetPreview({preview}:{preview:Any|null}){if(!preview)return null;return <article className="preview"><div className="section-head"><div><p className="eyebrow">STEP 2</p><h2>Check your uploaded data</h2></div><span className="muted">First {preview.rows.length} of {Number(preview.total_rows).toLocaleString()} rows</span></div><p className="hint">Use this preview to confirm headers, values, and which columns should be outcomes, predictors, groups, or categories.</p><div className="table-wrap"><table><thead><tr>{preview.columns.map((c:string)=><th key={c}>{c}</th>)}</tr></thead><tbody>{preview.rows.map((row:Any,i:number)=><tr key={i}>{preview.columns.map((c:string)=><td key={c}>{String(row[c]??'â€”')}</td>)}</tr>)}</tbody></table></div></article>}
function Picker({title,values,chosen,toggle}:{title:string,values:string[],chosen:string[],toggle:(x:string)=>void}){const [query,setQuery]=useState('');const shown=values.filter(v=>v.toLowerCase().includes(query.toLowerCase()));return <div className="picker"><div className="picker-head"><b>{title}</b><small>{chosen.length} selected</small></div>{values.length?<><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search variablesâ€¦"/><div className="variables">{shown.map(v=><label key={v}><input type="checkbox" checked={chosen.includes(v)} onChange={()=>toggle(v)}/>{v}</label>)}</div>{shown.length===0&&<p className="hint">No variables match that search.</p>}</>:<p className="hint">No suitable variables detected. You can correct types in Variable Explorer.</p>}</div>}
function Select({label,values,value,onChange}:{label:string,values:string[],value:string,onChange:(v:string)=>void}){return <label className="field">{label}<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Choose a variableâ€¦</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>}
function Configurator({method,numeric,categorical,allVariables,selected,setSelected,setA,setB,setSetA,setSetB,roles,setRoles,toggle}:Any){const role=(key:string)=>(v:string)=>setRoles((r:Any)=>({...r,[key]:v}));const numberRole=(key:string)=>(v:number)=>setRoles((r:Any)=>({...r,[key]:v}));if(method==='canonical'||method==='pls')return <div className="two-pickers"><Picker title={method==='pls'?'Predictors â€” X block':'Set A'} values={method==='pls'?numeric.filter(x=>!setB.includes(x)):numeric.filter(x=>!setB.includes(x))} chosen={setA} toggle={(x)=>toggle(x,setSetA)}/><Picker title={method==='pls'?'Outcomes â€” Y block':'Set B'} values={numeric.filter(x=>!setA.includes(x))} chosen={setB} toggle={(x)=>toggle(x,setSetB)}/></div>;if(method==='correspondence')return <div className="roles"><Select label="Row variable (first category)" values={categorical} value={roles.row} onChange={role('row')}/><Select label="Column variable (second category)" values={categorical.filter(x=>x!==roles.row)} value={roles.column} onChange={role('column')}/></div>;if(method==='manova')return <><Select label="Grouping variable (select your group column)" values={allVariables.filter(x=>!selected.includes(x))} value={roles.group} onChange={role('group')}/><Picker title="Dependent variables â€” select two or more" values={numeric} chosen={selected} toggle={(x)=>toggle(x,setSelected)}/></>;if(method==='discriminant')return <><Select label="Class / target group" values={categorical} value={roles.group} onChange={role('group')}/><Picker title="Numeric predictors" values={numeric} chosen={selected} toggle={(x)=>toggle(x,setSelected)}/></>;return <>{method==='regression'&&<Select label="Target / dependent variable" values={numeric} value={roles.outcome} onChange={role('outcome')}/>}<Picker title={method==='regression'?'Predictor variables':'Numeric variables'} values={method==='regression'?numeric.filter(x=>x!==roles.outcome):numeric} chosen={selected} toggle={(x)=>toggle(x,setSelected)}/>{method==='cluster'&&<div className="roles"><Select label="Clustering algorithm" values={['kmeans','hierarchical','dbscan','gmm','kmedoids']} value={roles.algorithm} onChange={role('algorithm')}/><NumberField label="Number of clusters" value={roles.clusters} onChange={numberRole('clusters')} min={2}/></div>}{method==='factor'&&<NumberField label="Factors to extract" value={roles.factors} onChange={numberRole('factors')} min={1}/>} {method==='ica'&&<NumberField label="Independent components" value={roles.components} onChange={numberRole('components')} min={1}/>}</>}
function NumberField({label,value,onChange,min}:{label:string,value:any,onChange:(v:number)=>void,min:number}){return <label className="field">{label}<input type="number" min={min} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function VariableExplorer({vars,typeOf,typeMap,setTypeMap}:Any){return <article className="explorer"><div className="section-head"><div><p className="eyebrow">STEP 2</p><h2>Variable Explorer</h2></div><span className="muted">Correct a type if needed</span></div><div className="variable-list">{vars.map((v:Any)=><div key={v.column}><div><b>{v.column}</b><small>{v.n_unique} unique Â· {v.n_missing} missing</small></div><select value={typeOf(v)} onChange={e=>setTypeMap((old:Any)=>({...old,[v.column]:e.target.value}))}>{['numeric','categorical','binary','ordinal','date','id'].map(t=><option key={t}>{t}</option>)}</select></div>)}</div></article>}
function CheckPanel({check}:{check:Any|null}){if(!check)return null;const all=[...(check.preconditions||[]),...(check.assumptions||[])];return <article className="check-panel"><div className="section-head"><div><p className="eyebrow">STEP 4</p><h2>{check.applicable?'Suitable to run':'Needs adjustment'}</h2></div><span className={check.applicable?'badge pass':'badge fail'}>{check.applicable?'READY':'CHECK REQUIRED'}</span></div>{check.errors?.map((e:string)=><p className="error" key={e}>{e}</p>)}<div className="checks">{all.map((a:Any,i:number)=><div className={a.status} key={i}><b>{a.status==='pass'?'âœ“':a.status==='warning'?'!':'Ã—'} {a.name}</b><small>{a.detail}</small></div>)}</div></article>}
function Recommendations({data,choose}:{data:Any,choose:(id:string)=>void}){return <article className="recommend"><h2>Recommended for this dataset</h2><p className="hint">These recommendations are based on available variable types. You still choose the question and variables.</p><div>{data.recommendations.filter((r:Any)=>r.status==='recommended').map((r:Any)=><button onClick={()=>choose(r.id)} key={r.id}>âœ“ <b>{r.name}</b><small>{r.reason}</small></button>)}</div></article>}
function Results({result}:{result:Any}){const rows=result.tables?.flatMap((t:Any)=>t.rows)||[];return <section className="results"><div className="section-head"><div><p className="eyebrow">STEP 5</p><h2>Results â€” {result.method}</h2></div>{rows.length>0&&<button className="secondary small" onClick={()=>download(rows,`${result.method.toLowerCase().replaceAll(' ','-')}-results.csv`)}>Download tables CSV</button>}</div>{result.errors?.length>0&&<div className="error">{result.errors.join(' ')}</div>}<div className="interpretation"><h3>Plain-language interpretation</h3><p>{result.interpretation||'No interpretation was returned.'}</p></div>{result.limitations?.length>0&&<details><summary>Important limitations</summary><ul>{result.limitations.map((x:string)=><li key={x}>{x}</li>)}</ul></details>}{result.tables?.map((t:Any)=><div className="table-wrap" key={t.name}><h3>{t.name}</h3><p className="hint">{t.description}</p><table><thead><tr>{t.columns.map((c:string)=><th key={c}>{c}</th>)}</tr></thead><tbody>{t.rows.map((r:Any,i:number)=><tr key={i}>{t.columns.map((c:string)=><td key={c}>{typeof r[c]==='number'?r[c].toFixed(4):String(r[c]??'â€”')}</td>)}</tr>)}</tbody></table></div>)}<div className="plots">{result.visualizations?.map((v:Any)=><div className="plot" key={v.id}><Plot data={v.spec.data} layout={{...v.spec.layout,autosize:true}} config={{responsive:true,displaylogo:false}} style={{width:'100%',height:'350px'}}/></div>)}</div><details><summary>View reproducible Python code</summary><pre>{result.python_code||'Code export is not yet available for this method.'}</pre></details></section>}

