import { useEffect, useMemo, useState } from 'react'
import { Bell, Menu, SlidersHorizontal, X, CloudRain, Thermometer, Droplet, Sun, Wind, Leaf, BarChart3, Zap, Calendar } from 'lucide-react'
import Plot from 'react-plotly.js'
import TimeSeriesDashboard from './TimeSeriesDashboard'
import SpatialAnalysis from './SpatialAnalysis'
import MultivariateStatistics from './MultivariateStatistics'
import { BALANCE, BLUEDROP, BOREHOLES, DCLASS, DAMS, GREENDROP, INDICES, NAV, ROADMAP, ROLES, SETTLEMENTS, SOURCES, STATIONS, TARIFFS, WQSITES, liveProvinces } from '../niwis/demoData'
import { BarChart, BarEl, DTag, LineChart, MapSVG } from '../niwis/svgCharts'
import '../niwis/niwis-portal.css'

const descriptions = {
  overview: ['National overview', 'A single operational picture of rainfall, drought, storage and water-security risk.', 'Situation'],
  drought: ['Drought status', 'Drought classification combines the latest available provincial climate observations.', 'Situation'],
  alerts: ['Alerts and early warning', 'Priority operational alerts requiring monitoring or response.', 'Situation'],
  studio: ['Analysis studio', 'Explore operational time-series, spatial and multivariate analysis in one workspace.', 'Situation'],
  satellite: ['Satellite & Remote Sensing Drought', 'Overview of satellite-derived drought indicators (NDVI, VHI, soil moisture).', 'Situation'],
  rainfall: ['Rainfall', 'Observed rainfall conditions and departures from the seasonal baseline.', 'Monitoring'],
  dams: ['Dams and reservoirs', 'Storage status for strategic national reservoirs.', 'Monitoring'],
  ai: ['Prediction engine', 'Climate-based provincial drought predictions generated by the connected model service.', 'Intelligence'],
  pipeline: ['Data integration', 'The connected data catalogue and the operational ingestion pipeline.', 'Platform'],
  roadmap: ['Implementation roadmap', 'A phased delivery plan for the National Integrated Water Information System.', 'Platform'],
}

function Panel({ title, source, children }) { return <section className="nw-panel"><div className="nw-phead"><h3>{title}</h3>{source && <span className="src">{source}</span>}</div>{children}</section> }
function Kpi({ label, value, unit, note, tone }) { return <article className={`nw-kpi ${tone || ''}`}><div className="lab">{label}</div><div className="val">{value}<small>{unit}</small></div>{note && <div className="delta">{note}</div>}</article> }
function Heading({ view }) { const [title, lede, crumb] = descriptions[view] || [view.replace(/\b\w/g, (v) => v.toUpperCase()), 'This NIWIS module is ready for its operational data connection.', 'NIWIS']; return <><div className="nw-crumb">{crumb} / {title}</div><h1 className="page">{title}</h1><p className="nw-lede">{lede}</p></> }

function Overview({ provinces, selectProvince }) {
  const chips = [
    { id: 'rain', label: 'Rainfall', unit: 'mm/day', Icon: CloudRain },
    { id: 'temp', label: 'Temperature', unit: '°C', Icon: Thermometer },
    { id: 'humid', label: 'Humidity', unit: '%', Icon: Droplet },
    { id: 'rad', label: 'Radiation', unit: 'W/m²', Icon: Sun },
    { id: 'wind', label: 'Wind Speed', unit: 'm/s', Icon: Wind },
    { id: 'pet', label: 'PET / ET', unit: 'mm/day', Icon: Leaf },
    { id: 'anom', label: 'Rainfall Anomaly', unit: '%', Icon: BarChart3 },
    { id: 'spi', label: 'SPI (1,3,6,12)', unit: 'dimensionless', Icon: Zap },
    { id: 'season', label: 'Seasonal Rainfall', unit: 'mm/season', Icon: Calendar },
  ]

  return (
    <>
      <div className="nw-overview-toolbar" aria-label="Climate variables">
        {chips.map((c) => (
          <button key={c.id} className="nw-overview-chip" type="button" aria-label={c.label}>
            <span className="nw-chip-icon"><c.Icon size={18} /></span>
            <span className="nw-chip-text"><span className="nw-chip-label">{c.label}</span><small className="nw-chip-unit">{c.unit}</small></span>
          </button>
        ))}
      </div>

      <div className="nw-overview-grid">
        <section className="nw-panel nw-overview-map">
          <div className="nw-panel-header">
            <span>Current SPI-3 Map (South Africa)</span>
            <span className="nw-panel-link">View</span>
          </div>
          <div className="nw-map-shell">
            <MapSVG provinces={provinces} selected={null} onSelect={selectProvince} colorFn={(p) => (DCLASS[p.d] || DCLASS['-']).c} />
            <div className="nw-map-legend">{['-', 'D0', 'D1', 'D2', 'D3'].map((d) => <span key={d}><i style={{ background: DCLASS[d].c }} />{d === '-' ? 'No drought' : d}</span>)}</div>
          </div>
        </section>

        <section className="nw-panel nw-overview-side">
          <div className="nw-panel-header">
            <span>Province Detail ? Gauteng</span>
            <span className="nw-panel-link">?</span>
          </div>
          <div className="nw-side-card-grid">
            <div className="nw-side-card"><span>Current SPI-3</span><strong>?</strong></div>
            <div className="nw-side-card"><span>Rainfall Anomaly</span><strong>?</strong></div>
            <div className="nw-side-card"><span>Temperature Anomaly</span><strong>?</strong></div>
            <div className="nw-side-card"><span>Forecast</span><strong>?</strong></div>
          </div>
          <div className="nw-side-block">
            <div className="nw-side-label">Drought Classification</div>
            <div className="nw-placeholder-bar" style={{ width: '100%' }} />
            <div className="nw-placeholder-bar" style={{ width: '62%' }} />
            <div className="nw-placeholder-bar" style={{ width: '48%' }} />
          </div>
          <div className="nw-side-block">
            <div className="nw-side-label">Key drivers</div>
            <div className="nw-driver-row"><span>Rainfall deficit</span><em>?</em></div>
            <div className="nw-driver-row"><span>High temperature</span><em>?</em></div>
            <div className="nw-driver-row"><span>Soil moisture deficit</span><em>?</em></div>
          </div>
        </section>

        <section className="nw-panel nw-overview-forecast">
          <div className="nw-panel-header">
            <span>Forecast ? Gauteng (SPI-3)</span>
            <span className="nw-panel-link">Projected</span>
          </div>
          <div className="nw-forecast-placeholder">
            <div className="nw-line-plot"><span className="nw-line-spark" /></div>
            <div className="nw-forecast-meta">
              <div><span>Forecast start</span><strong>?</strong></div>
              <div><span>Confidence range</span><strong>?</strong></div>
              <div><span>Historical</span><strong>?</strong></div>
            </div>
          </div>
        </section>
      </div>

      <div className="nw-overview-lower">
        <section className="nw-panel nw-summary-panel">
          <div className="nw-panel-header"><span>SPI-3 by Province (Current vs Forecast)</span></div>
          <div className="nw-placeholder-table">
            <div className="nw-row-label"><span>Province</span><span>?</span></div>
            <div className="nw-row-label"><span>Eastern Cape</span><span>?</span></div>
            <div className="nw-row-label"><span>Free State</span><span>?</span></div>
            <div className="nw-row-label"><span>KwaZulu-Natal</span><span>?</span></div>
          </div>
        </section>

        <section className="nw-panel nw-summary-panel">
          <div className="nw-panel-header"><span>Drought Forecast Summary</span></div>
          <div className="nw-placeholder-table compact">
            <div className="nw-row-label"><span>Forecast horizon</span><span>?</span></div>
            <div className="nw-row-label"><span>Target variable</span><span>?</span></div>
            <div className="nw-row-label"><span>Best model</span><span>?</span></div>
            <div className="nw-row-label"><span>Confidence</span><span>?</span></div>
          </div>
        </section>

        <section className="nw-panel nw-summary-panel">
          <div className="nw-panel-header"><span>Model Performance</span></div>
          <div className="nw-placeholder-bars">
            <div className="nw-model-row"><span>Model A</span><i style={{ width: '38%' }} /></div>
            <div className="nw-model-row"><span>Model B</span><i style={{ width: '56%' }} /></div>
            <div className="nw-model-row"><span>Model C</span><i style={{ width: '72%' }} /></div>
          </div>
        </section>

        <section className="nw-panel nw-summary-panel warning-panel">
          <div className="nw-panel-header"><span>Early Warning Alerts</span></div>
          <div className="nw-alert-stack">
            <div className="nw-mini-alert"><em className="dot-red" /> <span>?</span></div>
            <div className="nw-mini-alert"><em className="dot-amber" /> <span>?</span></div>
            <div className="nw-mini-alert"><em className="dot-cyan" /> <span>?</span></div>
          </div>
        </section>
      </div>
    </>
  )
}

function normaliseDistrictName(name = '') { return name.toLowerCase().replace(/[^a-z0-9]/g, '') }

function DistrictMap({ districts, values, colorFn, valueKey = 'NDVI', onSelect, selected }) {
  const project = ([lon, lat]) => [((lon - 16.45) / 16.5) * 680, ((-22.12 - lat) / 12.75) * 560]
  const ringsFor = (geometry) => geometry?.type === 'Polygon' ? [geometry.coordinates] : geometry?.type === 'MultiPolygon' ? geometry.coordinates : []
  const pathFor = (geometry) => ringsFor(geometry).flatMap((polygon) => polygon.map((ring) => ring.map((point, index) => {
    const [x, y] = project(point)
    return `${index ? 'L' : 'M'}${x.toFixed(1)},${y.toFixed(1)}`
  }).join(' ') + 'Z')).join(' ')
  const legend = MAP_LEGENDS[valueKey] || NDVI_LEGEND
  return <div className="sat-district-map"><svg viewBox="0 0 680 560" role="img" aria-label={`${legend.title} map`}>{districts.map((feature) => {
    const name = feature.properties?.shapeName || 'Unknown district'
    const value = values[normaliseDistrictName(name)]?.[valueKey]
    return <path key={feature.properties?.shapeID || name} d={pathFor(feature.geometry)} fill={value == null ? '#254251' : colorFn(value)} stroke={normaliseDistrictName(name) === normaliseDistrictName(selected) ? '#ffffff' : '#0a1b25'} strokeWidth={normaliseDistrictName(name) === normaliseDistrictName(selected) ? '2.4' : '.8'} onClick={() => onSelect(name)}><title>{`${name} · NDVI ${value == null ? 'No data' : value.toFixed(2)}`}</title></path>
  })}</svg><MapLegend {...legend} /></div>
}

function MapLegend({ title, gradient, items }) {
  return <aside className="map-color-legend" aria-label={`${title} color legend`} style={{ display: 'grid', alignContent: 'center', gap: 6, minWidth: 104, padding: '4px 2px', color: '#8fb7c8', fontSize: 9, lineHeight: 1.2 }}>
    <strong style={{ color: '#e4f4fa', fontSize: 10 }}>{title}</strong>
    <div style={{ display: 'grid', gridTemplateColumns: '10px 1fr', gap: 6, minHeight: 126 }}>
      <i style={{ display: 'block', width: 10, minHeight: 126, borderRadius: 3, background: gradient, border: '1px solid rgba(255,255,255,.25)' }} aria-hidden="true" />
      <ul style={{ display: 'grid', alignContent: 'space-between', margin: 0, padding: 0, listStyle: 'none' }}>{items.map(([range, meaning]) => <li key={range} style={{ display: 'grid', gap: 1 }}><b style={{ color: '#eef8fb', fontSize: 9 }}>{range}</b><span style={{ fontSize: 8 }}>{meaning}</span></li>)}</ul>
    </div>
  </aside>
}

const NDVI_LEGEND = { title: 'NDVI color scale', gradient: 'linear-gradient(180deg, #64c968, #f4dc45, #fa8c25, #f04444)', items: [['0.8-1.0', 'Very high'], ['0.6-0.8', 'High'], ['0.4-0.6', 'Moderate'], ['0.2-0.4', 'Low'], ['0.0-0.2', 'Very low']] }
const MOISTURE_LEGEND = { title: 'Soil moisture (m3/m3)', gradient: 'linear-gradient(180deg, #2d97c7, #4dc7c7, #75d36a, #f6ad3c)', items: [['0.19+', 'Very wet'], ['0.13-0.19', 'Wet'], ['0.08-0.13', 'Moderate'], ['Below 0.08', 'Dry']] }
const WATER_LEGEND = { title: 'Surface water extent (km2)', gradient: 'linear-gradient(180deg, #7be3ed, #25aac9, #226f92, #1d3441)', items: [['120+', 'Extensive'], ['45-120', 'High'], ['10-45', 'Moderate'], ['Below 10', 'Low']] }
const GRACE_LEGEND = { title: 'GRACE anomaly (cm)', gradient: 'linear-gradient(180deg, #3fa6d5, #62c977, #f5df4b, #fa9037, #e9474e)', items: [['5+', 'Very wet'], ['2-5', 'Wet'], ['-1 to 2', 'Near normal'], ['-4 to -1', 'Dry'], ['Below -4', 'Very dry']] }
const MAP_LEGENDS = { NDVI: NDVI_LEGEND, surface_soil_moisture: MOISTURE_LEGEND, rootzone_soil_moisture: MOISTURE_LEGEND, surface_water_extent_km2: WATER_LEGEND, GRACE_TWS: GRACE_LEGEND }

function Satellite({ provinces, selected, selectProvince }) {
  const values = { EC: .42, FS: .33, GT: .28, KZN: .45, LP: .42, MP: .41, NW: .36, NC: .22, WC: .46 }
  const [districts, setDistricts] = useState([])
  const [stationValues, setStationValues] = useState({})
  const [stationDate, setStationDate] = useState('')
  const [selectedDistrict, setSelectedDistrict] = useState('')
  const [districtHistory, setDistrictHistory] = useState([])
  useEffect(() => {
    Promise.all([fetch('/south_africa_adm2.geojson').then((response) => response.json()), fetch('/api/satellite/stations').then((response) => response.json())])
      .then(([geojson, satellite]) => {
        setDistricts(geojson.features || [])
        setStationValues(Object.fromEntries((satellite.stations || []).map((station) => [normaliseDistrictName(station.name), station])))
        setStationDate(satellite.date || '')
      }).catch(() => { setDistricts([]); setStationValues({}); setStationDate('') })
  }, [])
  useEffect(() => {
    if (!selectedDistrict) return
    fetch(`/api/satellite/history?district=${encodeURIComponent(selectedDistrict)}`).then((response) => response.ok ? response.json() : Promise.reject()).then((payload) => setDistrictHistory(payload.history || [])).catch(() => setDistrictHistory([]))
  }, [selectedDistrict])
  const p = provinces.find((item) => item.id === selected) || provinces.find((item) => item.id === 'GT') || provinces[0]
  const ndvi = values[p.id] || .28
  const vci = Math.round(ndvi * 85)
  const color = (v) => v < .28 ? '#f04444' : v < .36 ? '#fa8c25' : v < .43 ? '#f4dc45' : '#64c968'
  const moistureColor = (v) => v < .08 ? '#f6ad3c' : v < .13 ? '#75d36a' : v < .19 ? '#4dc7c7' : '#2d97c7'
  const waterColor = (v) => v < 10 ? '#1d3441' : v < 45 ? '#226f92' : v < 120 ? '#25aac9' : '#7be3ed'
  const graceColor = (v) => v < -4 ? '#e9474e' : v < -1 ? '#fa9037' : v < 2 ? '#f5df4b' : v < 5 ? '#62c977' : '#3fa6d5'
  const trend = [.45, .44, .49, .42, .36, .33, .31, .30, .28, .25, .23, .24, .26, .25, .22]
  const activeDistrict = selectedDistrict || districts[0]?.properties?.shapeName || ''
  const actual = stationValues[normaliseDistrictName(activeDistrict)] || {}
  const actualNdvi = actual.NDVI ?? ndvi
  const actualTrend = districtHistory.length ? districtHistory.slice(-15).map((row) => row.NDVI) : trend
  const metric = (icon, label, value, note) => <article className="sat-kpi" key={label}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>
  const detail = (icon, label, value, state) => <article className="sat-detail" key={label}><span>{icon}</span><div><small>{label}</small><strong>{value} <em>↓</em></strong><b>{state}</b></div></article>
  return <><Heading view="satellite" />
    <section className="sat-kpi-strip">{[metric('🌿', 'NDVI', actualNdvi.toFixed(2), 'latest district value'), metric('🌱', 'VCI', `${(actual.VCI ?? vci).toFixed(0)}%`, 'vegetation condition'), metric('✥', 'VHI', `${(actual.VHI ?? 32).toFixed(0)}%`, 'health index'), metric('🌡', 'TCI', `${(actual.TCI ?? 36).toFixed(0)}%`, 'temperature stress'), metric('💧', 'LST', `${(actual.LST ?? 32.4).toFixed(1)} °C`, 'land surface temp'), metric('≋', 'Soil Moisture (Surface)', `${(actual.surface_soil_moisture ?? .12).toFixed(2)} m³/m³`, 'surface moisture'), metric('💦', 'Root-zone Moisture', `${(actual.rootzone_soil_moisture ?? .08).toFixed(2)} m³/m³`, 'root-zone moisture'), metric('≋', 'NDWI', (actual.NDWI ?? -.18).toFixed(2), 'water condition'), metric('▰', 'Surface Water Extent', `${(actual.surface_water_extent_km2 ?? 4230).toFixed(0)} km²`, 'latest extent'), metric('◒', 'GRACE', `${(actual.GRACE_TWS ?? -1.6).toFixed(1)} cm`, 'water storage anomaly')]}</section>
    <div className="sat-top-grid"><Panel title="Current NDVI" source={stationDate ? `${districts.length} districts · ${stationDate}` : 'Vegetation Condition'}><p className="sat-caption">Click a district to load its latest satellite data and NDVI history.</p><div className="sat-map-wrap">{districts.length ? <DistrictMap districts={districts} values={stationValues} colorFn={color} selected={activeDistrict} onSelect={setSelectedDistrict} /> : <MapSVG provinces={provinces} selected={p.id} onSelect={selectProvince} colorFn={(item) => color(values[item.id] || .3)} />}<aside className="sat-scale"><span>NDVI value</span><i /><small>0.8–1.0 Very high<br />0.6–0.8 High<br />0.4–0.6 Moderate<br />0.2–0.4 Low<br />0.0–0.2 Very low</small></aside><NdviLegend /></div></Panel>
      <Panel title={`District Details – ${activeDistrict || 'Loading…'}`} source="Latest satelite.csv values"><div className="sat-detail-grid">{[detail('🌿', 'NDVI', actualNdvi.toFixed(2), 'Vegetation condition'), detail('🌱', 'VCI', `${(actual.VCI ?? vci).toFixed(1)}%`, 'Vegetation condition'), detail('✥', 'VHI', `${(actual.VHI ?? 32).toFixed(1)}%`, 'Vegetation health'), detail('🌡', 'TCI', `${(actual.TCI ?? 36).toFixed(1)}%`, 'Temperature condition'), detail('💧', 'Surface Soil Moisture', `${(actual.surface_soil_moisture ?? .12).toFixed(3)} m³/m³`, 'Latest value'), detail('💦', 'Root-zone Moisture', `${(actual.rootzone_soil_moisture ?? .08).toFixed(3)} m³/m³`, 'Latest value'), detail('≋', 'NDWI', (actual.NDWI ?? -.18).toFixed(2), 'Water condition'), detail('▰', 'Surface Water Extent', `${(actual.surface_water_extent_km2 ?? 0).toFixed(1)} km²`, 'Latest extent')]}</div></Panel>
      <Panel title={`Time Series – ${activeDistrict || 'District'}`} source="Actual NDVI history"><div className="sat-chart-tabs"><button className="sel">NDVI</button><button>3M</button><button>6M</button><button className="sel">1Y</button><button>2Y</button></div><div className="sat-chart"><b>NDVI Trend ({activeDistrict || 'District'})</b><LineChart sets={[{ n: 'NDVI', data: actualTrend, c: '#7cd957', w: 2.5, area: true }, { n: 'Historical mean', data: Array(actualTrend.length).fill(actualTrend.reduce((sum, value) => sum + value, 0) / actualTrend.length), c: '#78b5cf', dash: '4 4' }]} labels={districtHistory.slice(-15).map((row) => row.date.slice(0, 7)).concat(Array(Math.max(0, 15 - districtHistory.length)).fill(''))} min={0} max={.8} h={185} dec={1} /></div><div className="sat-chart-stats"><div><small>Latest NDVI</small><strong>{actualNdvi.toFixed(2)}</strong></div><div><small>Latest observation</small><strong>{stationDate || 'Loading…'}</strong></div></div><p className="sat-note">Values are loaded from the selected district in satelite.csv.</p></Panel></div>
    <div className="sat-bottom-grid"><Panel title="Satellite Indices – South Africa"><div className="sat-mini-tabs"><button className="sel">NDVI</button><button>VCI</button><button>VHI</button><button>TCI</button><button>LST</button></div><div className="sat-small-map">{districts.length ? <DistrictMap districts={districts} values={stationValues} colorFn={color} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><p className="sat-caption">Municipality-level NDVI. Click a region to inspect its latest value.</p></Panel><Panel title="Soil Moisture & Water Content"><div className="sat-dual-map"><div><small>Surface soil moisture</small>{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="surface_soil_moisture" colorFn={moistureColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><div><small>Root-zone soil moisture</small>{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="rootzone_soil_moisture" colorFn={moistureColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div></div><p className="sat-caption">Municipality-level values from the latest satellite observation.</p></Panel><Panel title="Surface Water Extent"><div className="sat-water-map">{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="surface_water_extent_km2" colorFn={waterColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><p className="sat-caption">Latest detected surface-water extent by municipality.</p></Panel><Panel title="GRACE Water Storage Anomaly"><div className="sat-small-map">{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="GRACE_TWS" colorFn={graceColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><p className="sat-caption">Latest GRACE total-water-storage anomaly by municipality.</p></Panel></div>
    <div className="sat-footer-grid"><Panel title="Key Insights"><ul className="sat-insights"><li>NDVI is 18% below the historical average in {p.name}.</li><li>Root-zone soil moisture is critically low at 0.08 m³/m³.</li><li>Surface water extent has decreased by 48% compared to baseline.</li><li>Water storage anomaly indicates significant depletion.</li></ul></Panel><Panel title="Drought Assessment (Satellite)"><div className="sat-assessment"><strong>D2<small>Severe Drought</small></strong><div><span>Overall condition <b>76%</b></span><BarEl v={76} color="#f9735b" /><span>Soil moisture deficit <b>68%</b></span><BarEl v={68} color="#f5b747" /><span>Water availability <b>54%</b></span><BarEl v={54} color="#fde047" /></div></div></Panel><Panel title="Model Integration"><p className="sat-caption">Satellite indicators are used to:</p><ul className="sat-checks"><li>Validate meteorological SPI-3</li><li>Improve forecast accuracy</li><li>Provide early warning signals</li></ul></Panel><Panel title="AI Summary"><p className="sat-caption">Satellite data shows widespread vegetation stress and reduced soil moisture in {p.name}. These conditions align with the current drought signal.</p><button className="nw-btn pri">View Detailed Analysis →</button></Panel></div></>
}

function SatellitePlaceholder({ provinces, selectProvince }) {
  return (
    <>
      <Heading view="satellite" />
      <div className="nw-overview-toolbar" style={{ marginBottom: 12 }}>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>NDVI</div>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>VCI</div>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>Soil moisture</div>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>LST</div>
      </div>

      <div className="nw-overview-grid">
        <section className="nw-panel nw-overview-map">
          <div className="nw-panel-header"><span>Satellite-derived NDVI (South Africa)</span><span className="nw-panel-link">View</span></div>
          <div className="nw-map-shell"><MapSVG provinces={provinces} selected={null} onSelect={selectProvince} colorFn={() => 'var(--ok)'} /><div style={{ height: 8 }} /></div>
        </section>

        <section className="nw-panel nw-overview-side">
          <div className="nw-panel-header"><span>Province metrics</span><span className="nw-panel-link">—</span></div>
          <div className="nw-side-card-grid">
            <div className="nw-side-card"><span>NDVI</span><strong>—</strong></div>
            <div className="nw-side-card"><span>VCI</span><strong>—</strong></div>
            <div className="nw-side-card"><span>Soil moisture</span><strong>—</strong></div>
            <div className="nw-side-card"><span>LST</span><strong>—</strong></div>
          </div>
        </section>

        <section className="nw-panel nw-overview-forecast">
          <div className="nw-panel-header"><span>Time series</span><span className="nw-panel-link">Projected</span></div>
          <div className="nw-forecast-placeholder"><div className="nw-line-plot" style={{ height: 220 }} /><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8, marginTop: 8 }}><div className="nw-side-card"><span>Latest</span><strong>—</strong></div><div className="nw-side-card"><span>Trend</span><strong>—</strong></div><div className="nw-side-card"><span>History</span><strong>—</strong></div></div></div>
        </section>
      </div>

      <div className="nw-overview-lower">
        <section className="nw-panel nw-summary-panel"><div className="nw-panel-header"><span>Satellite indices</span></div><div className="nw-placeholder-table"><div className="nw-row-label"><span>Index</span><span>—</span></div><div className="nw-row-label"><span>NDVI</span><span>—</span></div><div className="nw-row-label"><span>VCI</span><span>—</span></div></div></section>
        <section className="nw-panel nw-summary-panel"><div className="nw-panel-header"><span>Soil moisture map</span></div><div className="nw-placeholder-table"><div className="nw-row-label"><span>Surface</span><span>—</span></div><div className="nw-row-label"><span>Root-zone</span><span>—</span></div></div></section>
        <section className="nw-panel nw-summary-panel"><div className="nw-panel-header"><span>Surface water extent</span></div><div className="nw-placeholder-table"><div className="nw-row-label"><span>Detected water bodies</span><span>—</span></div></div></section>
        <section className="nw-panel nw-summary-panel warning-panel"><div className="nw-panel-header"><span>Alerts from EO</span></div><div className="nw-alert-stack"><div className="nw-mini-alert"><em className="dot-amber" /> <span>—</span></div></div></section>
      </div>
    </>
  )
}
function Drought({ provinces, selected, selectProvince }) { const p = provinces.find((x) => x.id === selected) || provinces[0]; return <><Heading view="drought" /><div className="nw-grid nw-gmap"><Panel title="Classification by province"><MapSVG provinces={provinces} selected={p.id} onSelect={selectProvince} colorFn={(x) => (DCLASS[x.d] || DCLASS['-']).c} /></Panel><Panel title={p.name} source={p.live ? 'Connected prediction' : 'Sample baseline'}><DTag d={p.d} /><div className="nw-grid nw-g2" style={{ marginTop: 14 }}><Kpi label="Consensus SPI" value={p.spi.toFixed(2)} /><Kpi label="Rainfall" value={p.rain.toFixed(1)} unit="mm" /></div><p className="nw-psub" style={{ marginTop: 14 }}>Catchment authority: {p.cma}. Select another province on the map to inspect its current classification.</p></Panel></div><div style={{ marginTop: 14 }}><Panel title="Provincial drought table"><table><thead><tr><th>Province</th><th>Classification</th><th className="nw-num">SPI</th><th className="nw-num">6-month rainfall</th></tr></thead><tbody>{provinces.map((x) => <tr key={x.id}><td>{x.name}</td><td><DTag d={x.d} /></td><td className="nw-num">{x.spi.toFixed(2)}</td><td className="nw-num">{x.rain6.toFixed(0)} mm</td></tr>)}</tbody></table></Panel></div></> }

function Alerts() { return <><Heading view="alerts" /><Panel title="Open alerts" source="Operations"><div>{[['Critical', 'Nqweba Dam has fallen below 8% full supply capacity.', 'Eastern Cape', 'var(--d4)'], ['Severe', 'Persistent rainfall deficit across the lower Orange catchment.', 'Northern Cape', 'var(--d2)'], ['Watch', 'Model confidence indicates worsening conditions within the next 30 days.', 'Western Cape', 'var(--d1)'], ['Information', 'Climate warehouse prediction refresh completed successfully.', 'National', 'var(--river)']].map(([level, text, area, color]) => <div className="nw-alertrow" key={text}><i className="sev" style={{ background: color }} /><div><b>{level} · {area}</b><p>{text}</p></div><time>Today</time></div>)}</div></Panel></> }

function Dams() { return <><Heading view="dams" /><Panel title="Strategic reservoir storage" source="Prototype catalogue"><div className="nw-tscroll"><table><thead><tr><th>Dam</th><th>Province</th><th className="nw-num">Capacity</th><th className="nw-num">Storage</th><th>Risk</th></tr></thead><tbody>{DAMS.map((d) => <tr key={d.n}><td>{d.n}</td><td>{d.p}</td><td className="nw-num">{d.cap.toLocaleString()} Mm³</td><td className="nw-num">{d.fsc.toFixed(1)}%</td><td><div style={{ minWidth: 100 }}><BarEl v={d.fsc} color={d.fsc < 30 ? 'var(--d3)' : d.fsc < 50 ? 'var(--d2)' : 'var(--ok)'} /></div></td></tr>)}</tbody></table></div></Panel></> }

const provinceSlugs = {
  'Eastern Cape': 'eastern-cape', 'Free State': 'free-state', Gauteng: 'gauteng',
  'KwaZulu-Natal': 'kwa-zulu-natal', Limpopo: 'limpopo', Mpumalanga: 'mpumalanga',
  'North West': 'north-west', 'Northern Cape': 'northern-cape', 'Western Cape': 'western-cape',
}

const forecastModels = [
  ['auto', 'NIWIS Auto-select'], ['sarima', 'SARIMA (seasonal ARIMA)'], ['arima', 'ARIMA'],
  ['sarimax', 'SARIMAX + Fourier'], ['ets', 'ETS / exponential smoothing'],
  ['prophet', 'Prophet'], ['harmonic', 'Harmonic regression'], ['ml', 'Gradient boosting'],
]

function ForecastWorkspace({ provinces }) {
  const [province, setProvince] = useState('KwaZulu-Natal')
  const [target, setTarget] = useState('daily_rainfall')
  const [model, setModel] = useState('auto')
  const [horizon, setHorizon] = useState(90)
  const [result, setResult] = useState(null)
  const [availableColumns, setAvailableColumns] = useState([])
  const [state, setState] = useState({ loading: false, error: '', note: '' })

  const runForecast = async () => {
    setState({ loading: true, error: '', note: 'Loading the selected province from the NIWIS climate warehouse…' })
    setResult(null)
    try {
      const loadResponse = await fetch(`/api/provinces/${provinceSlugs[province]}/load`, { method: 'POST' })
      const loaded = await loadResponse.json()
      if (!loadResponse.ok) throw new Error(loaded.detail || loaded.error || 'The province dataset could not be loaded.')
      const numeric = (loaded.columns || []).filter((column) => column.type === 'numeric').map((column) => column.name)
      const dateColumn = loaded.index_column || loaded.inferred_time_columns?.[0] || 'date'
      const resolvedTarget = numeric.includes(target) ? target : numeric.find((name) => /rainfall|precip/i.test(name)) || numeric[0]
      if (!resolvedTarget) throw new Error('The connected province dataset contains no numeric climate variables to forecast.')
      setAvailableColumns(numeric)
      setTarget(resolvedTarget)
      setState({ loading: true, error: '', note: `Fitting ${forecastModels.find(([id]) => id === model)?.[1]} to ${resolvedTarget}…` })
      const forecastResponse = await fetch('/api/forecast', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ dataset_id: loaded.dataset_id, date_column: dateColumn, target_column: resolvedTarget, model_type: model, forecast_steps: Number(horizon), include_confidence_intervals: true, confidence_level: .95 }),
      })
      const forecast = await forecastResponse.json()
      if (!forecastResponse.ok) throw new Error(forecast.detail || forecast.error || 'The forecasting service could not complete this request.')
      setResult(forecast)
      setState({ loading: false, error: '', note: `${forecast.history_values?.length || 0} observed records used · ${forecast.model_type} selected` })
    } catch (error) {
      setState({ loading: false, error: error.message || 'Unable to run the real-data forecast.', note: '' })
    }
  }

  const chartData = result ? [
    { x: result.history_dates, y: result.history_values, type: 'scatter', mode: 'lines', name: 'Observed', line: { color: '#5ac6e3', width: 2 } },
    ...(result.lower_bound && result.upper_bound ? [
      { x: result.forecast_dates, y: result.lower_bound, type: 'scatter', mode: 'lines', name: '95% lower', line: { color: 'rgba(140,123,224,0)', width: 0 }, hoverinfo: 'skip', showlegend: false },
      { x: result.forecast_dates, y: result.upper_bound, type: 'scatter', mode: 'lines', name: '95% confidence interval', fill: 'tonexty', fillcolor: 'rgba(140,123,224,.22)', line: { color: 'rgba(140,123,224,.35)', width: 1 } },
    ] : []),
    { x: result.forecast_dates, y: result.forecast_values, type: 'scatter', mode: 'lines', name: `Forecast · ${result.model_type}`, line: { color: '#f5b747', width: 2.5, dash: 'dash' } },
  ] : []

  return <><Heading view="ai" /><div className="nw-banner"><strong>Real-data forecast:</strong> this workspace loads the selected province from the connected NIWIS climate warehouse before it runs. It does not generate a chart until the backend returns actual observations and a forecast.</div><Panel title="Provincial forecasting" source="NIWIS climate warehouse + forecasting service"><div className="nw-forecast-controls"><label><span>Province</span><select value={province} onChange={(e) => setProvince(e.target.value)} disabled={state.loading}>{provinces.map((p) => <option key={p.id}>{p.name}</option>)}</select></label><label><span>Climate variable</span><select value={target} onChange={(e) => setTarget(e.target.value)} disabled={state.loading}>{(availableColumns.length ? availableColumns : ['daily_rainfall', 'daily_tmean', 'daily_tmin', 'daily_tmax', 'daily_pet']).map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label><label><span>Forecast model</span><select value={model} onChange={(e) => setModel(e.target.value)} disabled={state.loading}>{forecastModels.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Horizon</span><select value={horizon} onChange={(e) => setHorizon(e.target.value)} disabled={state.loading}>{[30, 90, 180, 365].map((days) => <option key={days} value={days}>{days} days</option>)}</select></label><button className="nw-btn pri nw-run-forecast" onClick={runForecast} disabled={state.loading}>{state.loading ? 'Running real-data forecast…' : 'Run forecast'}</button></div>{state.error && <div className="nw-error" style={{ marginTop: 14 }}>{state.error}</div>}{state.note && <p className="nw-note" style={{ margin: '12px 0 0' }}>{state.note}</p>}{result ? <><div className="nw-forecast-chart"><Plot data={chartData} layout={{ paper_bgcolor: 'transparent', plot_bgcolor: '#0d2029', font: { color: '#93AEBB', family: 'IBM Plex Sans' }, margin: { l: 50, r: 18, t: 25, b: 44 }, height: 390, xaxis: { gridcolor: '#1B3A49', tickfont: { size: 10 }, title: 'Date' }, yaxis: { gridcolor: '#1B3A49', title: target.replaceAll('_', ' ') }, legend: { orientation: 'h', y: 1.15 }, hovermode: 'x unified' }} config={{ displayModeBar: false, responsive: true }} useResizeHandler style={{ width: '100%' }} /></div><div className="nw-grid nw-g4"><Kpi label="Forecast model" value={result.model_type} /><Kpi label="Training records" value={result.model_performance?.training_points || result.history_values?.length || 0} /><Kpi label="Validation RMSE" value={Number(result.model_performance?.rmse || 0).toFixed(3)} /><Kpi label="Forecast horizon" value={result.forecast_steps} unit="days" /></div>{result.model_params?.warnings?.length ? <div className="nw-banner" style={{ marginTop: 14 }}><strong>Model note:</strong> {result.model_params.warnings.join(' ')}</div> : null}</> : <div className="nw-forecast-empty">Choose a province, climate variable and model, then run a forecast. The chart will show only returned warehouse observations and backend forecast values.</div>}</Panel></> }

function Prediction({ provinces }) { return <ForecastWorkspace provinces={provinces} /> }

function Pipeline() { return <><Heading view="pipeline" /><div className="nw-grid nw-g4"><Kpi label="Sources registered" value={SOURCES.length} /><Kpi label="Connected now" value={SOURCES.filter((s) => s.live).length} /><Kpi label="Ingestion health" value="99.1" unit="%" /><Kpi label="Model outputs" value="9" unit="provinces" /></div><div style={{ marginTop: 14 }}><Panel title="Source registry"><table><thead><tr><th>Source</th><th>Protocol</th><th>Frequency</th><th>Status</th></tr></thead><tbody>{SOURCES.map((s) => <tr key={s.n}><td>{s.n}</td><td>{s.proto}</td><td>{s.freq}</td><td><span className={`nw-tag ${s.live ? 't-ok' : 't-mute'}`}>{s.live ? 'Connected' : 'Pending connection'}</span></td></tr>)}</tbody></table></Panel></div></> }

function RoadmapView() { return <><Heading view="roadmap" /><div className="nw-grid nw-g3">{ROADMAP.map((p) => <Panel key={p.ph} title={p.ph} source={p.mo}><ul className="nw-tl">{p.items.map(([x, st]) => <li key={x} className={st === 'done' ? 'done' : st === 'now' ? 'now' : ''}>{x}<br /><span className="nw-note">{st === 'done' ? 'Complete' : st === 'now' ? 'In progress' : 'Planned'}</span></li>)}</ul></Panel>)}</div></> }

const catalogue = {
  rainfall: { title: 'Rainfall monitoring', intro: 'Latest provincial climate inputs used by the connected NIWIS prediction service.', cols: ['Province', 'Daily rainfall', '3-month accumulation', 'Data state'], rows: [['Eastern Cape', '42.5 mm', '130 mm', 'Connected model input'], ['Free State', '31.8 mm', '116 mm', 'Connected model input'], ['Gauteng', '28.6 mm', '124 mm', 'Connected model input'], ['KwaZulu-Natal', '51.3 mm', '182 mm', 'Connected model input']] },
  vegetation: { title: 'Vegetation condition', intro: 'Vegetation-condition products become available when the SANSA earth-observation feed is connected.', cols: ['Product', 'Resolution', 'Update cycle', 'State'], rows: [['Vegetation Condition Index', '10–30 m', 'Dekadal', 'Awaiting SANSA feed'], ['Vegetation Health Index', '1 km', 'Weekly', 'Awaiting SANSA feed'], ['Soil-moisture anomaly', '1 km', 'Daily', 'Awaiting SANSA feed']] },
  runoff: { title: 'Runoff monitoring', intro: 'Indicative river-flow conditions from the national gauging network.', cols: ['Station', 'Flow', 'Percentile', 'State'], rows: STATIONS.map((s) => [s.n, `${s.q} m³/s`, `${s.pct}%`, s.state]) },
  surface: { title: 'Surface water network', intro: 'Priority streamflow stations currently represented in the NIWIS catalogue.', cols: ['ID', 'Station', 'Discharge', 'State'], rows: STATIONS.map((s) => [s.id, s.n, `${s.q} m³/s`, s.state]) },
  groundwater: { title: 'Groundwater status', intro: 'Strategic boreholes and their current groundwater stress indicator.', cols: ['Borehole', 'Depth', 'SGI', 'Telemetry'], rows: BOREHOLES.map((s) => [s.n, `${s.depth} m bgl`, s.sgi.toFixed(2), s.tele ? 'Reporting' : 'Manual']) },
  climate: { title: 'Climate change', intro: 'Climate indicators and scenario products for long-range water-resource planning.', cols: ['Indicator', 'Baseline', 'Planning use', 'State'], rows: [['Temperature anomaly', '1981–2010', 'Heat and evaporation stress', 'Model input connected'], ['Rainfall anomaly', '1981–2010', 'Drought monitoring', 'Model input connected'], ['CMIP6 scenarios', 'SSP pathways', 'Long-term planning', 'Catalogue ready']] },
  quality: { title: 'Water quality', intro: 'National water-quality monitoring sites in the prototype catalogue.', cols: ['Site', 'Province', 'pH', 'Status'], rows: WQSITES.map((s) => [s.n, s.prov, s.ph.toFixed(1), s.st]) },
  bluedrop: { title: 'Drinking water — Blue Drop', intro: 'Drinking-water compliance overview for representative systems.', cols: ['Water services authority', 'Province', 'Compliance', 'Status'], rows: BLUEDROP.map((s) => [s.n, s.prov, `${s.comp}%`, s.st]) },
  greendrop: { title: 'Wastewater — Green Drop', intro: 'Wastewater works risk and load assessment.', cols: ['Works', 'Province', 'Load', 'Status'], rows: GREENDROP.map((s) => [s.n, s.prov, `${s.load}%`, s.st]) },
  rwqo: { title: 'Resource quality objectives', intro: 'Resource-quality objective categories for managed water systems.', cols: ['Objective', 'Measure', 'Application', 'State'], rows: [['Ecological reserve', 'Flow and quality bands', 'Catchment allocation', 'Catalogue available'], ['Domestic use', 'SANS 241 thresholds', 'Water services', 'Catalogue available'], ['Irrigation use', 'Salinity and microbial load', 'Agriculture', 'Catalogue available']] },
  balance: { title: 'Water balance and transfers', intro: 'National water balance inputs from the NIWIS prototype catalogue.', cols: ['Component', 'Code', 'Volume', 'Source'], rows: BALANCE.map((s) => [s[0], s[1], `${s[2].toLocaleString()} Mm³`, s[3]]) },
  tariffs: { title: 'Raw water tariffs', intro: 'Indicative charges by national water-resource scheme.', cols: ['Scheme', 'Raw water', 'Annual change', 'Users'], rows: TARIFFS.map((s) => [s.sch, `R ${s.raw.toFixed(2)}/m³`, `${s.d}%`, s.users]) },
  settlements: { title: 'Affected settlements', intro: 'Settlements requiring focused water-security monitoring.', cols: ['Settlement', 'Province', 'Days remaining', 'Risk'], rows: SETTLEMENTS.map((s) => [s.n, s.prov, s.days ? `${s.days} days` : 'Emergency', `${s.risk}%`]) },
  services: { title: 'Water services', intro: 'Water-services security signals linked to municipal and settlement reporting.', cols: ['Area', 'Supply source', 'Risk', 'Response'], rows: SETTLEMENTS.slice(0, 4).map((s) => [s.n, s.src, `${s.risk}%`, s.tank ? 'Tankering active' : 'Monitor']) },
  indices: { title: 'Index workbench', intro: 'The drought and water-resource indicators available in the NIWIS framework.', cols: ['Index', 'Name', 'Input', 'Use'], rows: INDICES },
  governance: { title: 'Data governance', intro: 'Quality, ownership, standards and access controls for operational NIWIS data.', cols: ['Control', 'Standard', 'Application', 'State'], rows: [['Metadata', 'ISO 19115', 'Published layers', 'Applied'], ['Geospatial services', 'OGC WMS/WFS', 'Data distribution', 'Applied'], ['Personal information', 'POPIA', 'Service data', 'Controlled'], ['Audit trail', '7-year retention', 'Platform actions', 'Applied']] },
  api: { title: 'Open data API', intro: 'Programmatic access to the NIWIS catalogue; endpoints are enabled as source systems connect.', cols: ['Endpoint', 'Output', 'Access', 'State'], rows: [['GET /api/predictions/latest', 'Provincial drought prediction', 'Portal proxy', 'Connected'], ['GET /v1/dams/{id}/storage', 'Storage series', 'Open', 'Catalogue ready'], ['GET /v1/indices/{index}', 'Drought indices', 'Open', 'Catalogue ready'], ['GET /wms', 'Map layers', 'Open', 'Catalogue ready']] },
  admin: { title: 'Administration', intro: 'Operational controls for source connections, roles and platform readiness.', cols: ['Area', 'Current state', 'Owner', 'Action'], rows: [['Prediction service', 'Connected', 'NIWIS model team', 'Monitor'], ['Climate warehouse', 'Connected', 'Data engineering', 'Monitor'], ['Hydrology feeds', 'Onboarding', 'DWS', 'Complete integration'], ['User roles', 'Prototype gate', 'Platform admin', 'Configure identity provider']] },
}

function CatalogueView({ view }) {
  const item = catalogue[view]
  const title = item?.title || view.replace(/\b\w/g, (letter) => letter.toUpperCase())
  const rows = item?.rows || [['Operational data connection', 'Pending', '—', 'Available in future feed']]
  const cols = item?.cols || ['Module', 'State', 'Last update', 'Next action']
  return <><Heading view={view} /><Panel title={title} source="NIWIS catalogue"><p className="nw-psub">{item?.intro || 'This operational module is represented in the NIWIS prototype catalogue.'}</p><div className="nw-tscroll"><table><thead><tr>{cols.map((col) => <th key={col}>{col}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={`${row[0]}-${i}`}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></Panel></>
}

function Studio({ studio, setStudio }) {
  const views = { timeseries: ['Time series', TimeSeriesDashboard], spatial: ['Spatial analysis', SpatialAnalysis], multivariate: ['Multivariate statistics', MultivariateStatistics] }
  const Active = views[studio][1]
  return <><Heading view="studio" /><div className="nw-chips">{Object.entries(views).map(([id, [label]]) => <button key={id} className={`nw-chip ${studio === id ? 'sel' : ''}`} onClick={() => setStudio(id)}>{label}</button>)}</div><div className="nw-banner"><strong>Integrated system:</strong> this is the existing analysis application running inside the new NIWIS portal.</div><Active /></>
}

export default function NIWISPortal() {
  const [entered, setEntered] = useState(false), [view, setView] = useState('overview'), [navOpen, setNavOpen] = useState(false), [selected, setSelected] = useState('EC'), [predictions, setPredictions] = useState([]), [studio, setStudio] = useState('timeseries')
  useEffect(() => { document.body.classList.add('nw-body'); return () => document.body.classList.remove('nw-body') }, [])
  useEffect(() => { fetch('/niwis-api/api/predictions/latest').then((r) => r.ok ? r.json() : Promise.reject()).then((r) => setPredictions(r.predictions || [])).catch(() => {}) }, [])
  const provinces = useMemo(() => liveProvinces(predictions), [predictions])
  const selectProvince = (id) => { setSelected(id); setView('drought') }
  const selectSatelliteProvince = (id) => setSelected(id)
  const content = view === 'overview' ? <Overview provinces={provinces} selectProvince={selectProvince} /> : view === 'drought' ? <Drought provinces={provinces} selected={selected} selectProvince={selectProvince} /> : view === 'alerts' ? <Alerts /> : view === 'dams' ? <Dams /> : view === 'ai' ? <Prediction provinces={provinces} /> : view === 'pipeline' ? <Pipeline /> : view === 'roadmap' ? <RoadmapView /> : view === 'satellite' ? <Satellite provinces={provinces} selected={selected} selectProvince={selectSatelliteProvince} /> : view === 'studio' ? <Studio studio={studio} setStudio={setStudio} /> : <CatalogueView view={view} />
  if (!entered) return <div className="nw"><div className="nw-gate"><div className="nw-gate-card"><div className="nw-gate-left"><div className="nw-crest"><div className="nw-crest-mark">NW</div><div><b>NIWIS</b><div className="nw-note">Department of Water and Sanitation</div></div></div><h1 className="nw-gate-title">National Integrated Water Information System</h1><p className="nw-gate-sub">One view of South Africa’s water: rainfall, dams, rivers, groundwater, quality and services — updated continuously and forecast ahead.</p><div className="nw-role-list">{ROLES.map((r) => <button className="nw-role" key={r.id} onClick={() => setEntered(true)}><i className="nw-role-key">{r.k}</i><div><b>{r.n}</b><span>{r.d}</span></div></button>)}</div><p className="nw-gate-note">Prototype portal. Live climate and prediction data are shown where the connected NIWIS service is available.</p></div><div className="nw-gate-right"><div className="nw-note">Platform status — 15 Sep 2026, 06:00 SAST</div>{[['Data sources registered', `${SOURCES.length}`], ['Telemetry stations reporting', '4 118'], ['Records ingested, last 24 h', '12.4 M'], ['Forecast models in production', '1'], ['Open alerts', '17']].map(([l, v]) => <div className="nw-gate-stat" key={l}><span>{l}</span><b className="mono">{v}</b></div>)}</div></div></div></div>
  return <div className="nw"><div className="nw-app"><header className="nw-topbar"><button className="nw-iconbtn" onClick={() => setNavOpen(!navOpen)} aria-label="Toggle menu"><Menu size={16} /></button><div className="nw-brand"><span className="nw-crest-mark">NW</span> NIWIS</div><div className="nw-statusstrip"><div className="nw-sstat"><em>NATIONAL DROUGHT</em><b>D2 · Severe</b></div><div className="nw-sstat"><em>CONNECTED DATA</em><b>{predictions.length ? 'Climate predictions' : 'Demo fallback'}</b></div></div><div className="nw-topactions"><span className="nw-pill live"><i className="nw-dot" />Live</span><button className="nw-iconbtn nw-alertbell" onClick={() => setView('alerts')}><Bell size={15} /><b>17</b></button><button className="nw-iconbtn" onClick={() => setEntered(false)}><SlidersHorizontal size={15} /></button></div></header><nav className={`nw-nav ${navOpen ? 'open' : ''}`}>{NAV.map(([group, items]) => <div key={group}><div className="nw-navgroup">{group}</div>{items.map(([id, label, num, live]) => <button key={id} className={`nw-navitem ${view === id ? 'sel' : ''}`} onClick={() => { setView(id); setNavOpen(false) }}><span className="nw-nid">{num}</span>{label}{live && <span className="nw-live">Live</span>}</button>)}</div>)}</nav><main className="nw-main">{content}</main></div></div>
}
