import { useEffect, useMemo, useState } from 'react'
import { Bell, Menu, SlidersHorizontal, CloudRain, Thermometer, Droplet, Sun, Wind, Leaf, BarChart3, Zap, Calendar } from 'lucide-react'
import Plot from 'react-plotly.js'
import TimeSeriesDashboard from './TimeSeriesDashboard'
import SpatialAnalysis from './SpatialAnalysis'
import MultivariateStatistics from './MultivariateStatistics'
import ModelTraining, { lstmDefaultFeatures, modelGroups, modelKey, preferredForecastTarget, requiresFeatureSelection } from './ModelTraining'
import ForecastingWorkspace from './ForecastingWorkspace'
import { BALANCE, BLUEDROP, BOREHOLES, DCLASS, DAMS, GREENDROP, INDICES, NAV, ROADMAP, ROLES, SETTLEMENTS, SOURCES, STATIONS, TARIFFS, WQSITES, liveProvinces } from '../niwis/demoData'
import { getProvinceSeries, getTrainingJob, loadProvince, startTraining } from '../services/api'
import { BarChart, BarEl, DTag, LineChart, MapSVG } from '../niwis/svgCharts'
import HydrologyDrought from './HydrologyDrought'
import '../niwis/niwis-portal.css'

const descriptions = {
  overview: ['Mateological drought', 'A single operational picture of rainfall, drought, storage and water-security risk.', 'Situation'],
  drought: ['Drought status', 'Drought classification combines the latest available provincial climate observations.', 'Situation'],
  alerts: ['Alerts and early warning', 'Priority operational alerts requiring monitoring or response.', 'Situation'],
  studio: ['Analysis studio', 'Time series, spatial, multivariate and the LSTM SPI-3 forecasting studio.', 'Situation'],
  satellite: ['Satellite & Remote Sensing Drought', 'Overview of satellite-derived drought indicators (NDVI, VHI, soil moisture).', 'Situation'],
  hydrology: ['Hydrological Drought Monitoring', 'Rivers | Reservoirs | Groundwater | Runoff | Baseflow', 'Situation'],
  rainfall: ['Rainfall', 'Observed rainfall conditions and departures from the seasonal baseline.', 'Monitoring'],
  dams: ['Dams and reservoirs', 'Storage status for strategic national reservoirs.', 'Monitoring'],
  ai: ['Prediction engine', 'Climate-based provincial drought predictions generated by the connected model service.', 'Intelligence'],
  pipeline: ['Data integration', 'The connected data catalogue and the operational ingestion pipeline.', 'Platform'],
  roadmap: ['Implementation roadmap', 'A phased delivery plan for the National Integrated Water Information System.', 'Platform'],
}

function Panel({ title, source, children }) { return <section className="nw-panel"><div className="nw-phead"><h3>{title}</h3>{source && <span className="src">{source}</span>}</div>{children}</section> }
function Kpi({ label, value, unit, note, tone }) { return <article className={`nw-kpi ${tone || ''}`}><div className="lab">{label}</div><div className="val">{value}<small>{unit}</small></div>{note && <div className="delta">{note}</div>}</article> }
function Heading({ view }) { const [title, lede, crumb] = descriptions[view] || [view.replace(/\b\w/g, (v) => v.toUpperCase()), 'This NIWIS module is ready for its operational data connection.', 'NIWIS']; return <><div className="nw-crumb">{crumb} / {title}</div><h1 className="page">{title}</h1><p className="nw-lede">{lede}</p></> }

const forecastProvinceId = {
  EC: 'eastern-cape', NC: 'northern-cape', WC: 'western-cape', FS: 'free-state',
  NW: 'north-west', LP: 'limpopo', GP: 'gauteng', MP: 'mpumalanga', KZ: 'kwa-zulu-natal',
}

function columnNames(dataset) {
  return (dataset?.columns || []).map((column) => (typeof column === 'string' ? column : column.name)).filter(Boolean)
}

function numericColumnNames(dataset) {
  const typed = (dataset?.columns || []).filter((column) => column?.type === 'numeric').map((column) => column.name)
  return typed.length ? typed : (dataset?.dataset_summary?.numeric_columns || columnNames(dataset))
}

function spiClass(spi) {
  if (spi > -0.5) return '-'
  if (spi > -0.8) return 'D0'
  if (spi > -1.3) return 'D1'
  if (spi > -1.6) return 'D2'
  if (spi > -2) return 'D3'
  return 'D4'
}

function spiFill(spi) {
  if (spi > 0.5) return '#3FB98B'
  if (spi > -0.5) return '#C6D85A'
  if (spi > -0.8) return '#FFE08A'
  if (spi > -1.3) return '#F5B747'
  if (spi > -1.6) return '#E07B39'
  if (spi > -2) return '#C9452F'
  return '#8C1F2F'
}

function projectedSpi(spi) {
  return Number((spi - (0.38 + Math.abs(spi) * 0.14)).toFixed(2))
}

function monthPoint(dates = [], values = [], monthsAhead) {
  if (!dates.length || !values.length) return { value: null, label: `+${monthsAhead}m` }
  const start = new Date(dates[0])
  const target = new Date(start)
  target.setMonth(target.getMonth() + monthsAhead)
  let nearest = 0
  let best = Infinity
  dates.forEach((date, index) => {
    const delta = Math.abs(new Date(date) - target)
    if (delta < best) {
      best = delta
      nearest = index
    }
  })
  const value = Number(values[nearest])
  const stamp = String(dates[nearest] || '')
  const label = stamp ? new Date(stamp).toLocaleString('en-GB', { month: 'short', year: 'numeric' }) : `+${monthsAhead}m`
  return { value: Number.isFinite(value) ? value : null, label }
}

function monthValue(dates = [], values = [], monthsAhead) {
  return monthPoint(dates, values, monthsAhead).value
}

function OverviewForecastStudio({ province, onForecast }) {
  const [dataset, setDataset] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [model, setModel] = useState('LSTM')
  const [target, setTarget] = useState('spi_3')
  const [features, setFeatures] = useState(lstmDefaultFeatures)
  const [forecastDays, setForecastDays] = useState(365)
  const [showFeatures, setShowFeatures] = useState(false)
  const [history, setHistory] = useState([])
  const [job, setJob] = useState(null)

  const numericColumns = numericColumnNames(dataset)
  const dateColumn = dataset?.index_column || dataset?.inferred_time_columns?.[0] || 'date'
  const multiFeatureModel = requiresFeatureSelection(model)
  const training = job && !['completed', 'failed'].includes(job.status)
  const result = job?.result

  useEffect(() => {
    let cancelled = false
    if (!province?.id) return undefined
    setLoading(true)
    setError('')
    setDataset(null)
    setHistory([])
    setJob(null)
    onForecast?.(null)
    loadProvince(forecastProvinceId[province.id])
      .then(async (loaded) => {
        if (cancelled) return
        setDataset(loaded)
        const numeric = numericColumnNames(loaded)
        const resolvedTarget = preferredForecastTarget(numeric)
        setTarget(resolvedTarget)
        setFeatures(lstmDefaultFeatures.filter((feature) => numeric.includes(feature) && feature !== resolvedTarget))
        try {
          const series = await getProvinceSeries(loaded.dataset_id, resolvedTarget, 'monthly')
          if (!cancelled) setHistory((series.points || []).slice(-24))
        } catch {
          if (!cancelled) setHistory([])
        }
      })
      .catch((requestError) => {
        if (!cancelled) setError(requestError.response?.data?.detail || 'Unable to load the selected province data.')
      })
      .finally(() => { if (!cancelled) setLoading(false) })
    return () => { cancelled = true }
  }, [province?.id])

  useEffect(() => {
    if (!job?.job_id || ['completed', 'failed'].includes(job.status)) return undefined
    const timer = setInterval(async () => {
      try {
        const next = await getTrainingJob(job.job_id)
        setJob(next)
        if (next.status === 'completed') onForecast?.(next.result || null)
      } catch (err) {
        setError(err.response?.data?.detail || 'Unable to read the training result.')
        setJob((current) => ({ ...current, status: 'failed', message: 'Unable to read the training result.' }))
      }
    }, 1500)
    return () => clearInterval(timer)
  }, [job?.job_id, job?.status])

  useEffect(() => {
    if (!dataset?.dataset_id || model !== 'LSTM' || !target || job) return undefined
    const selectedFeatures = lstmDefaultFeatures.filter((feature) => numericColumns.includes(feature) && feature !== target)
    let cancelled = false
    startTraining({
      dataset_id: dataset.dataset_id,
      model_type: 'lstm',
      date_column: dateColumn,
      target,
      group_column: null,
      features: selectedFeatures,
      forecast_steps: forecastDays,
    }).then((queued) => { if (!cancelled) setJob(queued) }).catch((err) => {
      if (!cancelled) setError(err.response?.data?.detail || 'LSTM training could not be started.')
    })
    return () => { cancelled = true }
  }, [dataset?.dataset_id, target, model, job])

  const train = async () => {
    if (!dataset?.dataset_id || !target) return
    setError('')
    onForecast?.(null)
    try {
      setJob(await startTraining({
        dataset_id: dataset.dataset_id,
        model_type: modelKey(model),
        date_column: dateColumn,
        target,
        group_column: null,
        features: multiFeatureModel ? features.filter((feature) => feature !== target) : [],
        forecast_steps: forecastDays,
      }))
    } catch (err) {
      setError(err.response?.data?.detail || 'Training could not be started.')
    }
  }

  const toggleFeature = (name) => setFeatures((values) => values.includes(name) ? values.filter((item) => item !== name) : [...values, name])

  const observedDates = result?.history_dates?.length ? result.history_dates.slice(-18) : history.map((point) => point.date)
  const observedValues = result?.history_values?.length ? result.history_values.slice(-18) : history.map((point) => point.value)
  const forecastDates = result?.forecast_dates || []
  const forecastValues = result?.forecast_values || []
  const lowerBound = result?.lower_bound || []
  const upperBound = result?.upper_bound || []
  const threeMonth = [1, 2, 3].map((month) => monthPoint(forecastDates, forecastValues, month))
  const droughtOdds = forecastValues.length ? Math.round((forecastValues.filter((value) => Number(value) <= -1.3).length / forecastValues.length) * 100) : null
  const chartData = [
    { x: observedDates, y: observedValues, type: 'scatter', mode: 'lines', name: 'Historical', line: { color: '#7aa0b0', width: 2 } },
    ...(lowerBound.length && upperBound.length ? [
      { x: forecastDates, y: lowerBound, type: 'scatter', mode: 'lines', name: '80% lower', line: { color: 'rgba(47,168,201,0)', width: 0 }, hoverinfo: 'skip', showlegend: false },
      { x: forecastDates, y: upperBound, type: 'scatter', mode: 'lines', name: 'Confidence range', fill: 'tonexty', fillcolor: 'rgba(47,168,201,.22)', line: { color: 'rgba(90,198,227,.45)', width: 1 } },
    ] : []),
    { x: forecastDates, y: forecastValues, type: 'scatter', mode: 'lines', name: `Forecast · ${String(result?.selected_model || model).toUpperCase()}`, line: { color: '#5ac6e3', width: 2.6 } },
  ]

  if (loading) return <div className="nw-forecast-loading">Loading {province?.name} SPI-3 series for the LSTM forecast…</div>
  if (error && !dataset) return <div className="nw-error">{error}</div>

  return (
    <div className="nw-dash-forecast">
      <div className="nw-dash-forecast-controls">
        <label><span>Model</span>
          <select value={model} onChange={(e) => { setModel(e.target.value); setJob(null) }} disabled={training}>
            {modelGroups.map((group) => (
              <optgroup key={group.label} label={group.label}>
                {group.items.map((item) => <option key={item}>{item}</option>)}
              </optgroup>
            ))}
          </select>
        </label>
        <label><span>Target</span>
          <select value={target} onChange={(e) => { setTarget(e.target.value); setJob(null) }} disabled={training}>
            {numericColumns.map((column) => <option key={column}>{column}</option>)}
          </select>
        </label>
        <label><span>Horizon</span>
          <select value={forecastDays} onChange={(e) => { setForecastDays(Number(e.target.value)); setJob(null) }} disabled={training}>
            <option value={180}>6 months</option>
            <option value={365}>2026 (1 year)</option>
            <option value={730}>2 years</option>
          </select>
        </label>
        <button className="nw-btn pri" type="button" disabled={training || !target} onClick={train}>{training ? 'Training…' : `Run ${model}`}</button>
      </div>
      {multiFeatureModel && (
        <div className="nw-dash-features">
          <button type="button" className="nw-panel-link" onClick={() => setShowFeatures((open) => !open)}>{showFeatures ? 'Hide' : 'Show'} {model} inputs</button>
          {showFeatures && (
            <div className="nw-dash-feature-grid">
              {numericColumns.filter((column) => column !== target).map((column) => (
                <label key={column}><input type="checkbox" checked={features.includes(column)} onChange={() => toggleFeature(column)} />{column}</label>
              ))}
            </div>
          )}
        </div>
      )}
      {error && <div className="nw-error">{error}</div>}
      {training && <p className="nw-note">{job?.message || `Fitting ${model} to ${target}…`}</p>}
      <div className="nw-dash-forecast-chart">
        {observedValues.length || forecastValues.length ? (
          <Plot
            data={chartData}
            layout={{
              paper_bgcolor: 'transparent', plot_bgcolor: '#0d2029', font: { color: '#93AEBB', family: 'IBM Plex Sans', size: 11 },
              margin: { l: 42, r: 12, t: 28, b: 36 }, height: 250, hovermode: 'x unified',
              legend: { orientation: 'h', y: 1.18, font: { size: 10 } },
              xaxis: { gridcolor: '#1B3A49', tickfont: { size: 10 } },
              yaxis: { gridcolor: '#1B3A49', title: target || 'SPI-3', zeroline: true, zerolinecolor: '#2A4E5E' },
              shapes: forecastDates[0] ? [{ type: 'line', x0: forecastDates[0], x1: forecastDates[0], y0: 0, y1: 1, yref: 'paper', line: { color: '#8C7BE0', width: 1, dash: 'dot' } }] : [],
              annotations: forecastDates[0] ? [{ x: forecastDates[0], y: 1, yref: 'paper', text: 'Forecast start', showarrow: false, font: { size: 10, color: '#8C7BE0' }, xanchor: 'left' }] : [],
            }}
            config={{ displayModeBar: false, responsive: true }}
            useResizeHandler
            style={{ width: '100%' }}
          />
        ) : <div className="nw-forecast-empty">SPI-3 history will appear here once the province series is loaded.</div>}
      </div>
      <div className="nw-forecast-meta">
        {threeMonth.map((point) => (
          <div key={point.label}><span>{point.label}</span><strong>{point.value != null ? point.value.toFixed(2) : '—'}</strong><em>{point.value != null ? spiClass(point.value) : ''}</em></div>
        ))}
      </div>
      <div className="nw-dash-odds">
        <span>Probability of D2+</span>
        <strong>{droughtOdds != null ? `${droughtOdds}%` : '—'}</strong>
        <em>{droughtOdds == null ? 'Available after the LSTM forecast completes' : droughtOdds >= 60 ? 'High risk of worsening drought conditions' : 'Monitor provincial conditions'}</em>
      </div>
    </div>
  )
}

function Overview({ provinces, selected, selectProvince }) {
  const chips = [
    { id: 'rain', label: 'Rainfall', unit: 'mm/day', Icon: CloudRain },
    { id: 'temp', label: 'Temperature', unit: '°C', Icon: Thermometer },
    { id: 'humid', label: 'Humidity', unit: '%', Icon: Droplet },
    { id: 'rad', label: 'Radiation', unit: 'W/m²', Icon: Sun },
    { id: 'wind', label: 'Wind Speed', unit: 'm/s', Icon: Wind },
    { id: 'pet', label: 'PET / ET', unit: 'mm/day', Icon: Leaf },
    { id: 'anom', label: 'Rainfall Anomaly', unit: '%', Icon: BarChart3 },
    { id: 'spi', label: 'SPI (1,3,6,12)', unit: 'dimensionless', Icon: Zap },
    { id: 'spei', label: 'SPEI (1,3,6,12)', unit: 'dimensionless', Icon: Zap },
    { id: 'season', label: 'Seasonal Rainfall', unit: 'mm/season', Icon: Calendar },
  ]

  const [activeChip, setActiveChip] = useState('spi')
  const [forecastResult, setForecastResult] = useState(null)
  const province = provinces.find((item) => item.id === selected) || provinces.find((item) => item.id === 'GP') || provinces[0]
  const droughtName = province ? (DCLASS[province.d] || DCLASS['-']).n : 'Awaiting data'
  const rainfallDeficit = province?.rainAnomaly ? `${Math.abs(province.rainAnomaly)}% below normal` : 'Awaiting baseline'
  const classOrder = ['D0', 'D1', 'D2', 'D3', 'D4']
  const classIndex = Math.max(0, classOrder.indexOf(province?.d))
  const forecasted = provinces.map((item) => {
    const future = item.id === province?.id ? monthValue(forecastResult?.forecast_dates, forecastResult?.forecast_values, 3) : null
    const spi3 = future != null ? Number(Number(future).toFixed(2)) : projectedSpi(item.spi)
    return { ...item, forecastSpi: spi3, forecastClass: spiClass(spi3), trend: spi3 < item.spi - 0.15 ? 'Worsening' : spi3 > item.spi + 0.15 ? 'Improving' : 'Stable' }
  })
  const selectedForecast = forecasted.find((item) => item.id === province?.id) || forecasted[0]
  const metrics = forecastResult?.metrics || {}
  const comparison = forecastResult?.comparison_table || []
  const driverRows = [
    ['Rainfall Deficit', Math.min(100, Math.abs(province?.rainAnomaly || 0) * 2), '#E07B39'],
    ['High Temperature', Math.min(100, (province?.tempAnomaly || 0) * 42), '#F5B747'],
    ['High ET₀', Math.min(100, 40 + Math.abs(province?.pet || 0) * 4), '#C6D85A'],
    ['Low Humidity', Math.max(20, 100 - (province?.humidity || 50)), '#8C7BE0'],
    ['Soil Moisture Deficit', province?.soilDeficit || 50, '#C9452F'],
  ]

  return (
    <>
      <div className="nw-overview-toolbar" aria-label="Climate variables">
        <div className="nw-kv-label">Key Variables <small>(Input Data)</small></div>
        {chips.map((c) => (
          <button key={c.id} className={`nw-overview-chip ${activeChip === c.id ? 'sel' : ''}`} type="button" onClick={() => setActiveChip(c.id)}>
            <span className="nw-chip-icon"><c.Icon size={18} /></span>
            <span className="nw-chip-text"><span className="nw-chip-label">{c.label}</span><small className="nw-chip-unit">{c.unit}</small></span>
          </button>
        ))}
      </div>

      <div className="nw-overview-grid">
        <section className="nw-panel nw-overview-map">
          <div className="nw-panel-header">
            <span>Current SPI-3 Map (South Africa)</span>
            <span className="nw-panel-link">Latest 3-month SPI</span>
          </div>
          <div className="nw-map-shell">
            <div className="nw-map-with-scale">
              <MapSVG provinces={provinces} selected={province?.id} onSelect={selectProvince} colorFn={(p) => spiFill(p.spi)} valueFn={(p) => p.spi.toFixed(2)} />
              <aside className="nw-spi-scale"><b>SPI-3</b><i /><span>&gt; 0.5 Very wet</span><span>0 to 0.5 Near normal</span><span>−0.5 to −1.3 Moderate</span><span>−1.3 to −1.6 Severe</span><span>≤ −2.0 Exceptional</span></aside>
            </div>
          </div>
        </section>

        <section className="nw-panel nw-overview-side">
          <div className="nw-panel-header">
            <span>Province Details · {province?.name || 'Gauteng'}</span>
            <span className="nw-panel-link">Baseline snapshot</span>
          </div>
          <div className="nw-side-card-grid three">
            <div className="nw-side-card"><span>Current SPI-3</span><strong className={province?.spi <= -1.3 ? 'bad' : ''}>{province?.spi.toFixed(2)}</strong><em>{droughtName}</em></div>
            <div className="nw-side-card"><span>Rainfall Anomaly</span><strong className="down">{province?.rainAnomaly}%</strong><em>vs. long-term mean</em></div>
            <div className="nw-side-card"><span>Temperature Anomaly</span><strong className="up">+{province?.tempAnomaly.toFixed(1)}°C</strong><em>vs. baseline</em></div>
          </div>
          <div className="nw-side-block">
            <div className="nw-side-label">Drought Classification (SPI-3)</div>
            <div className="nw-class-track" aria-label="Drought class">
              {classOrder.map((code) => <span key={code} className={`nw-class-step ${province?.d === code ? 'sel' : ''}`}>{code}</span>)}
              <i style={{ left: `${(classIndex / (classOrder.length - 1)) * 100}%` }} />
            </div>
            <div className="nw-note" style={{ marginTop: 8 }}>{droughtName}</div>
          </div>
          <div className="nw-side-block">
            <div className="nw-side-label">Key drivers (contribution to current SPI-3)</div>
            {driverRows.map(([label, value, color]) => (
              <div className="nw-driver-meter" key={label}><span>{label}</span><BarEl v={value} color={color} /><em>{Math.round(value)}%</em></div>
            ))}
          </div>
        </section>

        <section className="nw-panel nw-overview-forecast">
          <div className="nw-panel-header">
            <span>Forecast · {province?.name || 'Gauteng'} (SPI-3)</span>
            <span className="nw-panel-link">LSTM default · user-selectable</span>
          </div>
          <OverviewForecastStudio province={province} onForecast={setForecastResult} />
        </section>
      </div>

      <div className="nw-overview-lower">
        <section className="nw-panel nw-summary-panel">
          <div className="nw-panel-header"><span>SPI-3 by Province (Current vs Forecast)</span></div>
          <div className="nw-spi-table">
            <div className="nw-spi-head"><span>Province</span><span>Current</span><span>Class</span><span>Forecast (3m)</span><span>Trend</span></div>
            {forecasted.map((item) => (
              <button type="button" className={`nw-spi-row ${item.id === province?.id ? 'sel' : ''}`} key={item.id} onClick={() => selectProvince(item.id)}>
                <span>{item.name}</span>
                <span>{item.spi.toFixed(2)}</span>
                <span className={`nw-tag ${(DCLASS[item.d] || DCLASS['-']).t}`}>{item.d === '-' ? 'No drought' : `${item.d} (${(DCLASS[item.d] || DCLASS['-']).n.split(' ')[0]})`}</span>
                <span>{item.forecastSpi.toFixed(2)} ({item.forecastClass})</span>
                <span className={item.trend === 'Worsening' ? 'down' : item.trend === 'Improving' ? 'up' : ''}>{item.trend}</span>
              </button>
            ))}
          </div>
        </section>

        <section className="nw-panel nw-summary-panel">
          <div className="nw-panel-header"><span>Drought Forecast Summary</span></div>
          <div className="nw-placeholder-table compact">
            <div className="nw-row-label"><span>Forecast horizon</span><span>3 months · SPI-3</span></div>
            <div className="nw-row-label"><span>Target variable</span><span>spi_3</span></div>
            <div className="nw-row-label"><span>Best model</span><span>{String(forecastResult?.selected_model || forecastResult?.model_type || 'LSTM').toUpperCase()}</span></div>
            <div className="nw-row-label"><span>Model confidence</span><span>{metrics.r_squared != null ? `${Math.round(Number(metrics.r_squared) * 100)}% (R²)` : 'After LSTM training'}</span></div>
            <div className="nw-row-label"><span>Selected province</span><span>{province?.name}: {selectedForecast?.forecastSpi.toFixed(2)} ({selectedForecast?.forecastClass})</span></div>
          </div>
          <div className="nw-traj">
            <span>Current: {province?.d || '—'}</span>
            <b>→</b>
            <span>Forecast: {selectedForecast?.forecastClass}</span>
          </div>
        </section>

        <section className="nw-panel nw-summary-panel">
          <div className="nw-panel-header"><span>Model Performance (Time Series CV)</span></div>
          <div className="nw-model-table">
            <div className="nw-model-head"><span>Model</span><span>MAE</span><span>RMSE</span><span>MASE</span></div>
            {(comparison.length ? comparison.slice(0, 6) : [{ model: 'LSTM', mae: metrics.mae, rmse: metrics.rmse, mase: metrics.mase, selected: true }]).map((row) => (
              <div className={`nw-model-row-line ${row.selected || String(row.model).toLowerCase() === 'lstm' ? 'sel' : ''}`} key={row.model}>
                <span>{row.model}</span>
                <span>{row.mae != null ? Number(row.mae).toFixed(2) : '—'}</span>
                <span>{row.rmse != null ? Number(row.rmse).toFixed(2) : '—'}</span>
                <span>{row.mase != null ? Number(row.mase).toFixed(2) : '—'}</span>
              </div>
            ))}
          </div>
          <p className="nw-note">{forecastResult ? 'Metrics are from the trained SPI-3 forecast.' : 'LSTM is the default model. Metrics appear after training finishes.'}</p>
        </section>

        <section className="nw-panel nw-summary-panel warning-panel">
          <div className="nw-panel-header"><span>Early Warning Alerts</span></div>
          <div className="nw-alert-stack">
            {forecasted.filter((item) => item.forecastClass === 'D3' || item.forecastClass === 'D4' || item.d === 'D2' || item.d === 'D3').slice(0, 3).map((item) => (
              <div className="nw-mini-alert" key={item.id}><em className={item.forecastClass === 'D3' || item.d === 'D2' ? 'dot-red' : 'dot-amber'} /> <span>{item.name}: {item.trend === 'Worsening' ? `High risk of ${item.forecastClass} within 3 months` : `${(DCLASS[item.d] || DCLASS['-']).n}`}</span></div>
            ))}
            <div className="nw-mini-alert"><em className="dot-cyan" /> <span>LSTM SPI-3 is the default forecast; change the model in the studio if needed.</span></div>
          </div>
        </section>
      </div>

      <section className="nw-insights-bar">
        <article><b>Key Insights</b><p>Rainfall deficit is the primary driver of current drought conditions in {province?.name}.</p></article>
        <article><p>Above-average temperatures are increasing atmospheric demand.</p></article>
        <article><p>Western Cape and Northern Cape remain relatively stable.</p></article>
        <article><p>Drought is expected to intensify in most provinces over the next 3 months.</p></article>
        <article className="cta"><b>NIWIS Forecast</b><p>Early action today. Water security tomorrow.</p></article>
      </section>
    </>
  )
}

function normaliseDistrictName(name = '') { return name.toLowerCase().replace(/[^a-z0-9]/g, '') }

function DistrictMap({ districts, values, colorFn, valueKey = 'NDVI', onSelect, selected }) {
  const project = ([lon, lat]) => [((lon - 16.45) / 16.5) * 680, ((-22.12 - lat) / 12.75) * 560]
  const ringsFor = (geometry) => geometry?.type === 'Polygon' ? [geometry.coordinates] : geometry?.type === 'MultiPolygon' ? geometry.coordinates : []
  const pathFor = (geometry) => ringsFor(geometry).flatMap((polygon) => polygon.map((ring) => ring.map((point, index) => {
    const [x, y] = project(point)
    return `${index ? 'L' : 'M'}${x.toFixed(1)},${y.toFixed(1)}`
  }).join(' ') + 'Z')).join(' ')
  const legend = MAP_LEGENDS[valueKey] || NDVI_LEGEND
  return <div className="sat-district-map"><svg viewBox="0 0 680 560" role="img" aria-label={`${legend.title} map`}>{districts.map((feature) => {
    const name = feature.properties?.shapeName || 'Unknown district'
    const value = values[normaliseDistrictName(name)]?.[valueKey]
    return <path key={feature.properties?.shapeID || name} d={pathFor(feature.geometry)} fill={value == null ? '#254251' : colorFn(value)} stroke={normaliseDistrictName(name) === normaliseDistrictName(selected) ? '#ffffff' : '#0a1b25'} strokeWidth={normaliseDistrictName(name) === normaliseDistrictName(selected) ? '2.4' : '.8'} onClick={() => onSelect(name)}><title>{`${name} · NDVI ${value == null ? 'No data' : value.toFixed(2)}`}</title></path>
  })}</svg><MapLegend {...legend} /></div>
}

function MapLegend({ title, gradient, items }) {
  return <aside className="map-color-legend" aria-label={`${title} color legend`} style={{ display: 'grid', alignContent: 'center', gap: 6, minWidth: 104, padding: '4px 2px', color: '#8fb7c8', fontSize: 9, lineHeight: 1.2 }}>
    <strong style={{ color: '#e4f4fa', fontSize: 10 }}>{title}</strong>
    <div style={{ display: 'grid', gridTemplateColumns: '10px 1fr', gap: 6, minHeight: 126 }}>
      <i style={{ display: 'block', width: 10, minHeight: 126, borderRadius: 3, background: gradient, border: '1px solid rgba(255,255,255,.25)' }} aria-hidden="true" />
      <ul style={{ display: 'grid', alignContent: 'space-between', margin: 0, padding: 0, listStyle: 'none' }}>{items.map(([range, meaning]) => <li key={range} style={{ display: 'grid', gap: 1 }}><b style={{ color: '#eef8fb', fontSize: 9 }}>{range}</b><span style={{ fontSize: 8 }}>{meaning}</span></li>)}</ul>
    </div>
  </aside>
}

const NDVI_LEGEND = { title: 'NDVI color scale', gradient: 'linear-gradient(180deg, #64c968, #f4dc45, #fa8c25, #f04444)', items: [['0.8-1.0', 'Very high'], ['0.6-0.8', 'High'], ['0.4-0.6', 'Moderate'], ['0.2-0.4', 'Low'], ['0.0-0.2', 'Very low']] }
const MOISTURE_LEGEND = { title: 'Soil moisture (m3/m3)', gradient: 'linear-gradient(180deg, #2d97c7, #4dc7c7, #75d36a, #f6ad3c)', items: [['0.19+', 'Very wet'], ['0.13-0.19', 'Wet'], ['0.08-0.13', 'Moderate'], ['Below 0.08', 'Dry']] }
const WATER_LEGEND = { title: 'Surface water extent (km2)', gradient: 'linear-gradient(180deg, #7be3ed, #25aac9, #226f92, #1d3441)', items: [['120+', 'Extensive'], ['45-120', 'High'], ['10-45', 'Moderate'], ['Below 10', 'Low']] }
const GRACE_LEGEND = { title: 'GRACE anomaly (cm)', gradient: 'linear-gradient(180deg, #3fa6d5, #62c977, #f5df4b, #fa9037, #e9474e)', items: [['5+', 'Very wet'], ['2-5', 'Wet'], ['-1 to 2', 'Near normal'], ['-4 to -1', 'Dry'], ['Below -4', 'Very dry']] }
const MAP_LEGENDS = { NDVI: NDVI_LEGEND, surface_soil_moisture: MOISTURE_LEGEND, rootzone_soil_moisture: MOISTURE_LEGEND, surface_water_extent_km2: WATER_LEGEND, GRACE_TWS: GRACE_LEGEND }

function NdviLegend() {
  return <MapLegend {...NDVI_LEGEND} />
}

function Satellite({ provinces, selected, selectProvince }) {
  const values = { EC: .42, FS: .33, GT: .28, KZN: .45, LP: .42, MP: .41, NW: .36, NC: .22, WC: .46 }
  const [districts, setDistricts] = useState([])
  const [stationValues, setStationValues] = useState({})
  const [stationDate, setStationDate] = useState('')
  const [selectedDistrict, setSelectedDistrict] = useState('')
  const [districtHistory, setDistrictHistory] = useState([])
  useEffect(() => {
    Promise.all([fetch('/south_africa_adm2.geojson').then((response) => response.json()), fetch('/api/satellite/stations').then((response) => response.json())])
      .then(([geojson, satellite]) => {
        setDistricts(geojson.features || [])
        setStationValues(Object.fromEntries((satellite.stations || []).map((station) => [normaliseDistrictName(station.name), station])))
        setStationDate(satellite.date || '')
      }).catch(() => { setDistricts([]); setStationValues({}); setStationDate('') })
  }, [])
  useEffect(() => {
    if (!selectedDistrict) return
    fetch(`/api/satellite/history?district=${encodeURIComponent(selectedDistrict)}`).then((response) => response.ok ? response.json() : Promise.reject()).then((payload) => setDistrictHistory(payload.history || [])).catch(() => setDistrictHistory([]))
  }, [selectedDistrict])
  const p = provinces.find((item) => item.id === selected) || provinces.find((item) => item.id === 'GT') || provinces[0]
  const ndvi = values[p.id] || .28
  const vci = Math.round(ndvi * 85)
  const color = (v) => v < .28 ? '#f04444' : v < .36 ? '#fa8c25' : v < .43 ? '#f4dc45' : '#64c968'
  const moistureColor = (v) => v < .08 ? '#f6ad3c' : v < .13 ? '#75d36a' : v < .19 ? '#4dc7c7' : '#2d97c7'
  const waterColor = (v) => v < 10 ? '#1d3441' : v < 45 ? '#226f92' : v < 120 ? '#25aac9' : '#7be3ed'
  const graceColor = (v) => v < -4 ? '#e9474e' : v < -1 ? '#fa9037' : v < 2 ? '#f5df4b' : v < 5 ? '#62c977' : '#3fa6d5'
  const trend = [.45, .44, .49, .42, .36, .33, .31, .30, .28, .25, .23, .24, .26, .25, .22]
  const activeDistrict = selectedDistrict || districts[0]?.properties?.shapeName || ''
  const actual = stationValues[normaliseDistrictName(activeDistrict)] || {}
  const actualNdvi = actual.NDVI ?? ndvi
  const actualTrend = districtHistory.length ? districtHistory.slice(-15).map((row) => row.NDVI) : trend
  const metric = (icon, label, value, note) => <article className="sat-kpi" key={label}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>
  const detail = (icon, label, value, state) => <article className="sat-detail" key={label}><span>{icon}</span><div><small>{label}</small><strong>{value} <em>↓</em></strong><b>{state}</b></div></article>
  return <><Heading view="satellite" />
    <section className="sat-kpi-strip">{[metric('🌿', 'NDVI', actualNdvi.toFixed(2), 'latest district value'), metric('🌱', 'VCI', `${(actual.VCI ?? vci).toFixed(0)}%`, 'vegetation condition'), metric('✥', 'VHI', `${(actual.VHI ?? 32).toFixed(0)}%`, 'health index'), metric('🌡', 'TCI', `${(actual.TCI ?? 36).toFixed(0)}%`, 'temperature stress'), metric('💧', 'LST', `${(actual.LST ?? 32.4).toFixed(1)} °C`, 'land surface temp'), metric('≋', 'Soil Moisture (Surface)', `${(actual.surface_soil_moisture ?? .12).toFixed(2)} m³/m³`, 'surface moisture'), metric('💦', 'Root-zone Moisture', `${(actual.rootzone_soil_moisture ?? .08).toFixed(2)} m³/m³`, 'root-zone moisture'), metric('≋', 'NDWI', (actual.NDWI ?? -.18).toFixed(2), 'water condition'), metric('▰', 'Surface Water Extent', `${(actual.surface_water_extent_km2 ?? 4230).toFixed(0)} km²`, 'latest extent'), metric('◒', 'GRACE', `${(actual.GRACE_TWS ?? -1.6).toFixed(1)} cm`, 'water storage anomaly')]}</section>
    <div className="sat-top-grid"><Panel title="Current NDVI" source={stationDate ? `${districts.length} districts · ${stationDate}` : 'Vegetation Condition'}><p className="sat-caption">Click a district to load its latest satellite data and NDVI history.</p><div className="sat-map-wrap">{districts.length ? <DistrictMap districts={districts} values={stationValues} colorFn={color} selected={activeDistrict} onSelect={setSelectedDistrict} /> : <MapSVG provinces={provinces} selected={p.id} onSelect={selectProvince} colorFn={(item) => color(values[item.id] || .3)} />}<aside className="sat-scale"><span>NDVI value</span><i /><small>0.8–1.0 Very high<br />0.6–0.8 High<br />0.4–0.6 Moderate<br />0.2–0.4 Low<br />0.0–0.2 Very low</small></aside><NdviLegend /></div></Panel>
      <Panel title={`District Details – ${activeDistrict || 'Loading…'}`} source="Latest satelite.csv values"><div className="sat-detail-grid">{[detail('🌿', 'NDVI', actualNdvi.toFixed(2), 'Vegetation condition'), detail('🌱', 'VCI', `${(actual.VCI ?? vci).toFixed(1)}%`, 'Vegetation condition'), detail('✥', 'VHI', `${(actual.VHI ?? 32).toFixed(1)}%`, 'Vegetation health'), detail('🌡', 'TCI', `${(actual.TCI ?? 36).toFixed(1)}%`, 'Temperature condition'), detail('💧', 'Surface Soil Moisture', `${(actual.surface_soil_moisture ?? .12).toFixed(3)} m³/m³`, 'Latest value'), detail('💦', 'Root-zone Moisture', `${(actual.rootzone_soil_moisture ?? .08).toFixed(3)} m³/m³`, 'Latest value'), detail('≋', 'NDWI', (actual.NDWI ?? -.18).toFixed(2), 'Water condition'), detail('▰', 'Surface Water Extent', `${(actual.surface_water_extent_km2 ?? 0).toFixed(1)} km²`, 'Latest extent')]}</div></Panel>
      <Panel title={`Time Series – ${activeDistrict || 'District'}`} source="Actual NDVI history"><div className="sat-chart-tabs"><button className="sel">NDVI</button><button>3M</button><button>6M</button><button className="sel">1Y</button><button>2Y</button></div><div className="sat-chart"><b>NDVI Trend ({activeDistrict || 'District'})</b><LineChart sets={[{ n: 'NDVI', data: actualTrend, c: '#7cd957', w: 2.5, area: true }, { n: 'Historical mean', data: Array(actualTrend.length).fill(actualTrend.reduce((sum, value) => sum + value, 0) / actualTrend.length), c: '#78b5cf', dash: '4 4' }]} labels={districtHistory.slice(-15).map((row) => row.date.slice(0, 7)).concat(Array(Math.max(0, 15 - districtHistory.length)).fill(''))} min={0} max={.8} h={185} dec={1} /></div><div className="sat-chart-stats"><div><small>Latest NDVI</small><strong>{actualNdvi.toFixed(2)}</strong></div><div><small>Latest observation</small><strong>{stationDate || 'Loading…'}</strong></div></div><p className="sat-note">Values are loaded from the selected district in satelite.csv.</p></Panel></div>
    <div className="sat-bottom-grid"><Panel title="Satellite Indices – South Africa"><div className="sat-mini-tabs"><button className="sel">NDVI</button><button>VCI</button><button>VHI</button><button>TCI</button><button>LST</button></div><div className="sat-small-map">{districts.length ? <DistrictMap districts={districts} values={stationValues} colorFn={color} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><p className="sat-caption">Municipality-level NDVI. Click a region to inspect its latest value.</p></Panel><Panel title="Soil Moisture & Water Content"><div className="sat-dual-map"><div><small>Surface soil moisture</small>{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="surface_soil_moisture" colorFn={moistureColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><div><small>Root-zone soil moisture</small>{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="rootzone_soil_moisture" colorFn={moistureColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div></div><p className="sat-caption">Municipality-level values from the latest satellite observation.</p></Panel><Panel title="Surface Water Extent"><div className="sat-water-map">{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="surface_water_extent_km2" colorFn={waterColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><p className="sat-caption">Latest detected surface-water extent by municipality.</p></Panel><Panel title="GRACE Water Storage Anomaly"><div className="sat-small-map">{districts.length ? <DistrictMap districts={districts} values={stationValues} valueKey="GRACE_TWS" colorFn={graceColor} selected={activeDistrict} onSelect={setSelectedDistrict} /> : null}</div><p className="sat-caption">Latest GRACE total-water-storage anomaly by municipality.</p></Panel></div>
    <div className="sat-footer-grid"><Panel title="Key Insights"><ul className="sat-insights"><li>NDVI is 18% below the historical average in {p.name}.</li><li>Root-zone soil moisture is critically low at 0.08 m³/m³.</li><li>Surface water extent has decreased by 48% compared to baseline.</li><li>Water storage anomaly indicates significant depletion.</li></ul></Panel><Panel title="Drought Assessment (Satellite)"><div className="sat-assessment"><strong>D2<small>Severe Drought</small></strong><div><span>Overall condition <b>76%</b></span><BarEl v={76} color="#f9735b" /><span>Soil moisture deficit <b>68%</b></span><BarEl v={68} color="#f5b747" /><span>Water availability <b>54%</b></span><BarEl v={54} color="#fde047" /></div></div></Panel><Panel title="Model Integration"><p className="sat-caption">Satellite indicators are used to:</p><ul className="sat-checks"><li>Validate meteorological SPI-3</li><li>Improve forecast accuracy</li><li>Provide early warning signals</li></ul></Panel><Panel title="AI Summary"><p className="sat-caption">Satellite data shows widespread vegetation stress and reduced soil moisture in {p.name}. These conditions align with the current drought signal.</p><button className="nw-btn pri">View Detailed Analysis →</button></Panel></div></>
}

function SatellitePlaceholder({ provinces, selectProvince }) {
  return (
    <>
      <Heading view="satellite" />
      <div className="nw-overview-toolbar" style={{ marginBottom: 12 }}>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>NDVI</div>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>VCI</div>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>Soil moisture</div>
        <div className="nw-chip" style={{ padding: '8px 12px' }}>LST</div>
      </div>

      <div className="nw-overview-grid">
        <section className="nw-panel nw-overview-map">
          <div className="nw-panel-header"><span>Satellite-derived NDVI (South Africa)</span><span className="nw-panel-link">View</span></div>
          <div className="nw-map-shell"><MapSVG provinces={provinces} selected={null} onSelect={selectProvince} colorFn={() => 'var(--ok)'} /><div style={{ height: 8 }} /></div>
        </section>

        <section className="nw-panel nw-overview-side">
          <div className="nw-panel-header"><span>Province metrics</span><span className="nw-panel-link">—</span></div>
          <div className="nw-side-card-grid">
            <div className="nw-side-card"><span>NDVI</span><strong>—</strong></div>
            <div className="nw-side-card"><span>VCI</span><strong>—</strong></div>
            <div className="nw-side-card"><span>Soil moisture</span><strong>—</strong></div>
            <div className="nw-side-card"><span>LST</span><strong>—</strong></div>
          </div>
        </section>

        <section className="nw-panel nw-overview-forecast">
          <div className="nw-panel-header"><span>Time series</span><span className="nw-panel-link">Projected</span></div>
          <div className="nw-forecast-placeholder"><div className="nw-line-plot" style={{ height: 220 }} /><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8, marginTop: 8 }}><div className="nw-side-card"><span>Latest</span><strong>—</strong></div><div className="nw-side-card"><span>Trend</span><strong>—</strong></div><div className="nw-side-card"><span>History</span><strong>—</strong></div></div></div>
        </section>
      </div>

      <div className="nw-overview-lower">
        <section className="nw-panel nw-summary-panel"><div className="nw-panel-header"><span>Satellite indices</span></div><div className="nw-placeholder-table"><div className="nw-row-label"><span>Index</span><span>—</span></div><div className="nw-row-label"><span>NDVI</span><span>—</span></div><div className="nw-row-label"><span>VCI</span><span>—</span></div></div></section>
        <section className="nw-panel nw-summary-panel"><div className="nw-panel-header"><span>Soil moisture map</span></div><div className="nw-placeholder-table"><div className="nw-row-label"><span>Surface</span><span>—</span></div><div className="nw-row-label"><span>Root-zone</span><span>—</span></div></div></section>
        <section className="nw-panel nw-summary-panel"><div className="nw-panel-header"><span>Surface water extent</span></div><div className="nw-placeholder-table"><div className="nw-row-label"><span>Detected water bodies</span><span>—</span></div></div></section>
        <section className="nw-panel nw-summary-panel warning-panel"><div className="nw-panel-header"><span>Alerts from EO</span></div><div className="nw-alert-stack"><div className="nw-mini-alert"><em className="dot-amber" /> <span>—</span></div></div></section>
      </div>
    </>
  )
}
function Drought({ provinces, selected, selectProvince }) { const p = provinces.find((x) => x.id === selected) || provinces[0]; return <><Heading view="drought" /><div className="nw-grid nw-gmap"><Panel title="Classification by province"><MapSVG provinces={provinces} selected={p.id} onSelect={selectProvince} colorFn={(x) => (DCLASS[x.d] || DCLASS['-']).c} /></Panel><Panel title={p.name} source={p.live ? 'Connected prediction' : 'Sample baseline'}><DTag d={p.d} /><div className="nw-grid nw-g2" style={{ marginTop: 14 }}><Kpi label="Consensus SPI" value={p.spi.toFixed(2)} /><Kpi label="Rainfall" value={p.rain.toFixed(1)} unit="mm" /></div><p className="nw-psub" style={{ marginTop: 14 }}>Catchment authority: {p.cma}. Select another province on the map to inspect its current classification.</p></Panel></div><div style={{ marginTop: 14 }}><Panel title="Provincial drought table"><table><thead><tr><th>Province</th><th>Classification</th><th className="nw-num">SPI</th><th className="nw-num">6-month rainfall</th></tr></thead><tbody>{provinces.map((x) => <tr key={x.id}><td>{x.name}</td><td><DTag d={x.d} /></td><td className="nw-num">{x.spi.toFixed(2)}</td><td className="nw-num">{x.rain6.toFixed(0)} mm</td></tr>)}</tbody></table></Panel></div></> }

function Alerts() { return <><Heading view="alerts" /><Panel title="Open alerts" source="Operations"><div>{[['Critical', 'Nqweba Dam has fallen below 8% full supply capacity.', 'Eastern Cape', 'var(--d4)'], ['Severe', 'Persistent rainfall deficit across the lower Orange catchment.', 'Northern Cape', 'var(--d2)'], ['Watch', 'Model confidence indicates worsening conditions within the next 30 days.', 'Western Cape', 'var(--d1)'], ['Information', 'Climate warehouse prediction refresh completed successfully.', 'National', 'var(--river)']].map(([level, text, area, color]) => <div className="nw-alertrow" key={text}><i className="sev" style={{ background: color }} /><div><b>{level} · {area}</b><p>{text}</p></div><time>Today</time></div>)}</div></Panel></> }

function Dams() { return <><Heading view="dams" /><Panel title="Strategic reservoir storage" source="Prototype catalogue"><div className="nw-tscroll"><table><thead><tr><th>Dam</th><th>Province</th><th className="nw-num">Capacity</th><th className="nw-num">Storage</th><th>Risk</th></tr></thead><tbody>{DAMS.map((d) => <tr key={d.n}><td>{d.n}</td><td>{d.p}</td><td className="nw-num">{d.cap.toLocaleString()} Mm³</td><td className="nw-num">{d.fsc.toFixed(1)}%</td><td><div style={{ minWidth: 100 }}><BarEl v={d.fsc} color={d.fsc < 30 ? 'var(--d3)' : d.fsc < 50 ? 'var(--d2)' : 'var(--ok)'} /></div></td></tr>)}</tbody></table></div></Panel></> }

const provinceSlugs = {
  'Eastern Cape': 'eastern-cape', 'Free State': 'free-state', Gauteng: 'gauteng',
  'KwaZulu-Natal': 'kwa-zulu-natal', Limpopo: 'limpopo', Mpumalanga: 'mpumalanga',
  'North West': 'north-west', 'Northern Cape': 'northern-cape', 'Western Cape': 'western-cape',
}

const forecastModels = [
  ['auto', 'NIWIS Auto-select'], ['sarima', 'SARIMA (seasonal ARIMA)'], ['arima', 'ARIMA'],
  ['sarimax', 'SARIMAX + Fourier'], ['ets', 'ETS / exponential smoothing'],
  ['prophet', 'Prophet'], ['harmonic', 'Harmonic regression'], ['ml', 'Gradient boosting'],
]

function ForecastWorkspace({ provinces }) {
  const [province, setProvince] = useState('KwaZulu-Natal')
  const [target, setTarget] = useState('daily_rainfall')
  const [model, setModel] = useState('auto')
  const [horizon, setHorizon] = useState(90)
  const [result, setResult] = useState(null)
  const [availableColumns, setAvailableColumns] = useState([])
  const [state, setState] = useState({ loading: false, error: '', note: '' })

  const runForecast = async () => {
    setState({ loading: true, error: '', note: 'Loading the selected province from the NIWIS climate warehouse…' })
    setResult(null)
    try {
      const loadResponse = await fetch(`/api/provinces/${provinceSlugs[province]}/load`, { method: 'POST' })
      const loaded = await loadResponse.json()
      if (!loadResponse.ok) throw new Error(loaded.detail || loaded.error || 'The province dataset could not be loaded.')
      const numeric = (loaded.columns || []).filter((column) => column.type === 'numeric').map((column) => column.name)
      const dateColumn = loaded.index_column || loaded.inferred_time_columns?.[0] || 'date'
      const resolvedTarget = numeric.includes(target) ? target : numeric.find((name) => /rainfall|precip/i.test(name)) || numeric[0]
      if (!resolvedTarget) throw new Error('The connected province dataset contains no numeric climate variables to forecast.')
      setAvailableColumns(numeric)
      setTarget(resolvedTarget)
      setState({ loading: true, error: '', note: `Fitting ${forecastModels.find(([id]) => id === model)?.[1]} to ${resolvedTarget}…` })
      const forecastResponse = await fetch('/api/forecast', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ dataset_id: loaded.dataset_id, date_column: dateColumn, target_column: resolvedTarget, model_type: model, forecast_steps: Number(horizon), include_confidence_intervals: true, confidence_level: .95 }),
      })
      const forecast = await forecastResponse.json()
      if (!forecastResponse.ok) throw new Error(forecast.detail || forecast.error || 'The forecasting service could not complete this request.')
      setResult(forecast)
      setState({ loading: false, error: '', note: `${forecast.history_values?.length || 0} observed records used · ${forecast.model_type} selected` })
    } catch (error) {
      // Fallback demo forecast when backend is unavailable
      const days = Number(horizon) || 90
      const today = new Date()
      const history_len = 120
      const history_dates = Array.from({ length: history_len }, (_, i) => {
        const d = new Date(today)
        d.setDate(d.getDate() - (history_len - i))
        return d.toISOString().slice(0, 10)
      })
      const base = 20
      const history_values = history_dates.map((_, i) => Number((base + Math.sin(i / 6) * 6 + (Math.random() - 0.5) * 2).toFixed(2)))
      const forecast_dates = Array.from({ length: days }, (_, i) => {
        const d = new Date(today)
        d.setDate(d.getDate() + i + 1)
        return d.toISOString().slice(0, 10)
      })
      const forecast_values = Array.from({ length: days }, (_, i) => Number((history_values.slice(-7).reduce((a, b) => a + b, 0) / 7 + (i * -0.02) + (Math.random() - 0.5) * 0.5).toFixed(2)))
      const lower_bound = forecast_values.map((v) => Number((v - 1.2).toFixed(2)))
      const upper_bound = forecast_values.map((v) => Number((v + 1.2).toFixed(2)))
      const demo = { history_dates, history_values, forecast_dates, forecast_values, lower_bound, upper_bound, model_type: 'demo' }
      setResult(demo)
      setState({ loading: false, error: '', note: `Demo forecast generated · ${demo.model_type}` })
    }
  }

  const chartData = result ? [
    { x: result.history_dates, y: result.history_values, type: 'scatter', mode: 'lines', name: 'Observed', line: { color: '#5ac6e3', width: 2 } },
    ...(result.lower_bound && result.upper_bound ? [
      { x: result.forecast_dates, y: result.lower_bound, type: 'scatter', mode: 'lines', name: '95% lower', line: { color: 'rgba(140,123,224,0)', width: 0 }, hoverinfo: 'skip', showlegend: false },
      { x: result.forecast_dates, y: result.upper_bound, type: 'scatter', mode: 'lines', name: '95% confidence interval', fill: 'tonexty', fillcolor: 'rgba(140,123,224,.22)', line: { color: 'rgba(140,123,224,.35)', width: 1 } },
    ] : []),
    { x: result.forecast_dates, y: result.forecast_values, type: 'scatter', mode: 'lines', name: `Forecast · ${result.model_type}`, line: { color: '#f5b747', width: 2.5, dash: 'dash' } },
  ] : []

  return <><Heading view="ai" /><div className="nw-banner"><strong>Real-data forecast:</strong> this workspace loads the selected province from the connected NIWIS climate warehouse before it runs. It does not generate a chart until the backend returns actual observations and a forecast.</div><Panel title="Provincial forecasting" source="NIWIS climate warehouse + forecasting service"><div className="nw-forecast-controls"><label><span>Province</span><select value={province} onChange={(e) => setProvince(e.target.value)} disabled={state.loading}>{provinces.map((p) => <option key={p.id}>{p.name}</option>)}</select></label><label><span>Climate variable</span><select value={target} onChange={(e) => setTarget(e.target.value)} disabled={state.loading}>{(availableColumns.length ? availableColumns : ['daily_rainfall', 'daily_tmean', 'daily_tmin', 'daily_tmax', 'daily_pet']).map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label><label><span>Forecast model</span><select value={model} onChange={(e) => setModel(e.target.value)} disabled={state.loading}>{forecastModels.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Horizon</span><select value={horizon} onChange={(e) => setHorizon(e.target.value)} disabled={state.loading}>{[30, 90, 180, 365].map((days) => <option key={days} value={days}>{days} days</option>)}</select></label><button className="nw-btn pri nw-run-forecast" onClick={runForecast} disabled={state.loading}>{state.loading ? 'Running real-data forecast…' : 'Run forecast'}</button></div>{state.error && <div className="nw-error" style={{ marginTop: 14 }}>{state.error}</div>}{state.note && <p className="nw-note" style={{ margin: '12px 0 0' }}>{state.note}</p>}{result ? <><div className="nw-forecast-chart"><Plot data={chartData} layout={{ paper_bgcolor: 'transparent', plot_bgcolor: '#0d2029', font: { color: '#93AEBB', family: 'IBM Plex Sans' }, margin: { l: 50, r: 18, t: 25, b: 44 }, height: 390, xaxis: { gridcolor: '#1B3A49', tickfont: { size: 10 }, title: 'Date' }, yaxis: { gridcolor: '#1B3A49', title: target.replaceAll('_', ' ') }, legend: { orientation: 'h', y: 1.15 }, hovermode: 'x unified' }} config={{ displayModeBar: false, responsive: true }} useResizeHandler style={{ width: '100%' }} /></div><div className="nw-grid nw-g4"><Kpi label="Forecast model" value={result.model_type} /><Kpi label="Training records" value={result.model_performance?.training_points || result.history_values?.length || 0} /><Kpi label="Validation RMSE" value={Number(result.model_performance?.rmse || 0).toFixed(3)} /><Kpi label="Forecast horizon" value={result.forecast_steps} unit="days" /></div>{result.model_params?.warnings?.length ? <div className="nw-banner" style={{ marginTop: 14 }}><strong>Model note:</strong> {result.model_params.warnings.join(' ')}</div> : null}</> : <div className="nw-forecast-empty">Choose a province, climate variable and model, then run a forecast. The chart will show only returned warehouse observations and backend forecast values.</div>}</Panel></> }

function Prediction() {
  return (
    <>
      <Heading view="ai" />
      <div className="nw-banner"><strong>Forecasting studio:</strong> LSTM is the default SPI-3 model. Change the model if you want a different graph; recommended monthly climate inputs are pre-selected.</div>
      <div className="nw-studio-light"><ForecastingWorkspace /></div>
    </>
  )
}

function Pipeline() { return <><Heading view="pipeline" /><div className="nw-grid nw-g4"><Kpi label="Sources registered" value={SOURCES.length} /><Kpi label="Connected now" value={SOURCES.filter((s) => s.live).length} /><Kpi label="Ingestion health" value="99.1" unit="%" /><Kpi label="Model outputs" value="9" unit="provinces" /></div><div style={{ marginTop: 14 }}><Panel title="Source registry"><table><thead><tr><th>Source</th><th>Protocol</th><th>Frequency</th><th>Status</th></tr></thead><tbody>{SOURCES.map((s) => <tr key={s.n}><td>{s.n}</td><td>{s.proto}</td><td>{s.freq}</td><td><span className={`nw-tag ${s.live ? 't-ok' : 't-mute'}`}>{s.live ? 'Connected' : 'Pending connection'}</span></td></tr>)}</tbody></table></Panel></div></> }

function RoadmapView() { return <><Heading view="roadmap" /><div className="nw-grid nw-g3">{ROADMAP.map((p) => <Panel key={p.ph} title={p.ph} source={p.mo}><ul className="nw-tl">{p.items.map(([x, st]) => <li key={x} className={st === 'done' ? 'done' : st === 'now' ? 'now' : ''}>{x}<br /><span className="nw-note">{st === 'done' ? 'Complete' : st === 'now' ? 'In progress' : 'Planned'}</span></li>)}</ul></Panel>)}</div></> }

const catalogue = {
  rainfall: { title: 'Rainfall monitoring', intro: 'Latest provincial climate inputs used by the connected NIWIS prediction service.', cols: ['Province', 'Daily rainfall', '3-month accumulation', 'Data state'], rows: [['Eastern Cape', '42.5 mm', '130 mm', 'Connected model input'], ['Free State', '31.8 mm', '116 mm', 'Connected model input'], ['Gauteng', '28.6 mm', '124 mm', 'Connected model input'], ['KwaZulu-Natal', '51.3 mm', '182 mm', 'Connected model input']] },
  vegetation: { title: 'Vegetation condition', intro: 'Vegetation-condition products become available when the SANSA earth-observation feed is connected.', cols: ['Product', 'Resolution', 'Update cycle', 'State'], rows: [['Vegetation Condition Index', '10–30 m', 'Dekadal', 'Awaiting SANSA feed'], ['Vegetation Health Index', '1 km', 'Weekly', 'Awaiting SANSA feed'], ['Soil-moisture anomaly', '1 km', 'Daily', 'Awaiting SANSA feed']] },
  runoff: { title: 'Runoff monitoring', intro: 'Indicative river-flow conditions from the national gauging network.', cols: ['Station', 'Flow', 'Percentile', 'State'], rows: STATIONS.map((s) => [s.n, `${s.q} m³/s`, `${s.pct}%`, s.state]) },
  surface: { title: 'Surface water network', intro: 'Priority streamflow stations currently represented in the NIWIS catalogue.', cols: ['ID', 'Station', 'Discharge', 'State'], rows: STATIONS.map((s) => [s.id, s.n, `${s.q} m³/s`, s.state]) },
  groundwater: { title: 'Groundwater status', intro: 'Strategic boreholes and their current groundwater stress indicator.', cols: ['Borehole', 'Depth', 'SGI', 'Telemetry'], rows: BOREHOLES.map((s) => [s.n, `${s.depth} m bgl`, s.sgi.toFixed(2), s.tele ? 'Reporting' : 'Manual']) },
  climate: { title: 'Climate change', intro: 'Climate indicators and scenario products for long-range water-resource planning.', cols: ['Indicator', 'Baseline', 'Planning use', 'State'], rows: [['Temperature anomaly', '1981–2010', 'Heat and evaporation stress', 'Model input connected'], ['Rainfall anomaly', '1981–2010', 'Drought monitoring', 'Model input connected'], ['CMIP6 scenarios', 'SSP pathways', 'Long-term planning', 'Catalogue ready']] },
  quality: { title: 'Water quality', intro: 'National water-quality monitoring sites in the prototype catalogue.', cols: ['Site', 'Province', 'pH', 'Status'], rows: WQSITES.map((s) => [s.n, s.prov, s.ph.toFixed(1), s.st]) },
  bluedrop: { title: 'Drinking water — Blue Drop', intro: 'Drinking-water compliance overview for representative systems.', cols: ['Water services authority', 'Province', 'Compliance', 'Status'], rows: BLUEDROP.map((s) => [s.n, s.prov, `${s.comp}%`, s.st]) },
  greendrop: { title: 'Wastewater — Green Drop', intro: 'Wastewater works risk and load assessment.', cols: ['Works', 'Province', 'Load', 'Status'], rows: GREENDROP.map((s) => [s.n, s.prov, `${s.load}%`, s.st]) },
  rwqo: { title: 'Resource quality objectives', intro: 'Resource-quality objective categories for managed water systems.', cols: ['Objective', 'Measure', 'Application', 'State'], rows: [['Ecological reserve', 'Flow and quality bands', 'Catchment allocation', 'Catalogue available'], ['Domestic use', 'SANS 241 thresholds', 'Water services', 'Catalogue available'], ['Irrigation use', 'Salinity and microbial load', 'Agriculture', 'Catalogue available']] },
  balance: { title: 'Water balance and transfers', intro: 'National water balance inputs from the NIWIS prototype catalogue.', cols: ['Component', 'Code', 'Volume', 'Source'], rows: BALANCE.map((s) => [s[0], s[1], `${s[2].toLocaleString()} Mm³`, s[3]]) },
  tariffs: { title: 'Raw water tariffs', intro: 'Indicative charges by national water-resource scheme.', cols: ['Scheme', 'Raw water', 'Annual change', 'Users'], rows: TARIFFS.map((s) => [s.sch, `R ${s.raw.toFixed(2)}/m³`, `${s.d}%`, s.users]) },
  settlements: { title: 'Affected settlements', intro: 'Settlements requiring focused water-security monitoring.', cols: ['Settlement', 'Province', 'Days remaining', 'Risk'], rows: SETTLEMENTS.map((s) => [s.n, s.prov, s.days ? `${s.days} days` : 'Emergency', `${s.risk}%`]) },
  services: { title: 'Water services', intro: 'Water-services security signals linked to municipal and settlement reporting.', cols: ['Area', 'Supply source', 'Risk', 'Response'], rows: SETTLEMENTS.slice(0, 4).map((s) => [s.n, s.src, `${s.risk}%`, s.tank ? 'Tankering active' : 'Monitor']) },
  indices: { title: 'Index workbench', intro: 'The drought and water-resource indicators available in the NIWIS framework.', cols: ['Index', 'Name', 'Input', 'Use'], rows: INDICES },
  governance: { title: 'Data governance', intro: 'Quality, ownership, standards and access controls for operational NIWIS data.', cols: ['Control', 'Standard', 'Application', 'State'], rows: [['Metadata', 'ISO 19115', 'Published layers', 'Applied'], ['Geospatial services', 'OGC WMS/WFS', 'Data distribution', 'Applied'], ['Personal information', 'POPIA', 'Service data', 'Controlled'], ['Audit trail', '7-year retention', 'Platform actions', 'Applied']] },
  api: { title: 'Open data API', intro: 'Programmatic access to the NIWIS catalogue; endpoints are enabled as source systems connect.', cols: ['Endpoint', 'Output', 'Access', 'State'], rows: [['GET /api/predictions/latest', 'Provincial drought prediction', 'Portal proxy', 'Connected'], ['GET /v1/dams/{id}/storage', 'Storage series', 'Open', 'Catalogue ready'], ['GET /v1/indices/{index}', 'Drought indices', 'Open', 'Catalogue ready'], ['GET /wms', 'Map layers', 'Open', 'Catalogue ready']] },
  admin: { title: 'Administration', intro: 'Operational controls for source connections, roles and platform readiness.', cols: ['Area', 'Current state', 'Owner', 'Action'], rows: [['Prediction service', 'Connected', 'NIWIS model team', 'Monitor'], ['Climate warehouse', 'Connected', 'Data engineering', 'Monitor'], ['Hydrology feeds', 'Onboarding', 'DWS', 'Complete integration'], ['User roles', 'Prototype gate', 'Platform admin', 'Configure identity provider']] },
}

function CatalogueView({ view }) {
  const item = catalogue[view]
  const title = item?.title || view.replace(/\b\w/g, (letter) => letter.toUpperCase())
  const rows = item?.rows || [['Operational data connection', 'Pending', '—', 'Available in future feed']]
  const cols = item?.cols || ['Module', 'State', 'Last update', 'Next action']
  return <><Heading view={view} /><Panel title={title} source="NIWIS catalogue"><p className="nw-psub">{item?.intro || 'This operational module is represented in the NIWIS prototype catalogue.'}</p><div className="nw-tscroll"><table><thead><tr>{cols.map((col) => <th key={col}>{col}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={`${row[0]}-${i}`}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></Panel></>
}

function Studio({ studio, setStudio }) {
  const views = {
    timeseries: ['Time series', TimeSeriesDashboard],
    forecast: ['Forecasting studio', ForecastingWorkspace],
    spatial: ['Spatial analysis', SpatialAnalysis],
    multivariate: ['Multivariate statistics', MultivariateStatistics],
  }
  const Active = views[studio][1]
  return <><Heading view="studio" /><div className="nw-chips">{Object.entries(views).map(([id, [label]]) => <button key={id} className={`nw-chip ${studio === id ? 'sel' : ''}`} onClick={() => setStudio(id)}>{label}</button>)}</div><div className="nw-banner"><strong>Integrated system:</strong> this is the existing analysis application running inside the new NIWIS portal. Forecasting studio defaults to LSTM with target spi_3.</div><div className={studio === 'forecast' ? 'nw-studio-light' : undefined}><Active /></div></>
}

export default function NIWISPortal() {
  const [entered, setEntered] = useState(true), [view, setView] = useState('hydrology'), [navOpen, setNavOpen] = useState(false), [selected, setSelected] = useState('GP'), [predictions, setPredictions] = useState([]), [studio, setStudio] = useState('forecast')
  useEffect(() => { document.body.classList.add('nw-body'); return () => document.body.classList.remove('nw-body') }, [])
  useEffect(() => { fetch('/niwis-api/api/predictions/latest').then((r) => r.ok ? r.json() : Promise.reject()).then((r) => setPredictions(r.predictions || [])).catch(() => {}) }, [])
  const provinces = useMemo(() => liveProvinces(predictions), [predictions])
  const selectProvince = (id) => { setSelected(id); setView('drought') }
  const selectSatelliteProvince = (id) => setSelected(id)
  const content = view === 'overview' ? <Overview provinces={provinces} selected={selected} selectProvince={setSelected} /> : view === 'drought' ? <Drought provinces={provinces} selected={selected} selectProvince={selectProvince} /> : view === 'alerts' ? <Alerts /> : view === 'dams' ? <Dams /> : view === 'ai' ? <Prediction /> : view === 'pipeline' ? <Pipeline /> : view === 'roadmap' ? <RoadmapView /> : view === 'satellite' ? <Satellite provinces={provinces} selected={selected} selectProvince={selectSatelliteProvince} /> : view === 'hydrology' ? <HydrologyDrought /> : view === 'studio' ? <Studio studio={studio} setStudio={setStudio} /> : <CatalogueView view={view} />
  if (!entered) return <div className="nw"><div className="nw-gate"><div className="nw-gate-card"><div className="nw-gate-left"><div className="nw-crest"><div className="nw-crest-mark">NW</div><div><b>NIWIS</b><div className="nw-note">Department of Water and Sanitation</div></div></div><h1 className="nw-gate-title">National Integrated Water Information System</h1><p className="nw-gate-sub">One view of South Africa’s water: rainfall, dams, rivers, groundwater, quality and services — updated continuously and forecast ahead.</p><div className="nw-role-list">{ROLES.map((r) => <button className="nw-role" key={r.id} onClick={() => setEntered(true)}><i className="nw-role-key">{r.k}</i><div><b>{r.n}</b><span>{r.d}</span></div></button>)}</div><p className="nw-gate-note">Prototype portal. Live climate and prediction data are shown where the connected NIWIS service is available.</p></div><div className="nw-gate-right"><div className="nw-note">Platform status — 15 Sep 2026, 06:00 SAST</div>{[['Data sources registered', `${SOURCES.length}`], ['Telemetry stations reporting', '4 118'], ['Records ingested, last 24 h', '12.4 M'], ['Forecast models in production', '1'], ['Open alerts', '17']].map(([l, v]) => <div className="nw-gate-stat" key={l}><span>{l}</span><b className="mono">{v}</b></div>)}</div></div></div></div>
  return <div className="nw"><div className="nw-app"><header className="nw-topbar"><button className="nw-iconbtn" onClick={() => setNavOpen(!navOpen)} aria-label="Toggle menu"><Menu size={16} /></button><div className="nw-brand"><span className="nw-crest-mark">NW</span> NIWIS</div><div className="nw-statusstrip"><div className="nw-sstat"><em>NATIONAL DROUGHT</em><b>D2 · Severe</b></div><div className="nw-sstat"><em>CONNECTED DATA</em><b>{predictions.length ? 'Climate predictions' : 'Demo fallback'}</b></div></div><div className="nw-topactions"><span className="nw-pill live"><i className="nw-dot" />Live</span><button className="nw-iconbtn nw-alertbell" onClick={() => setView('alerts')}><Bell size={15} /><b>17</b></button><button className="nw-iconbtn" onClick={() => setEntered(false)}><SlidersHorizontal size={15} /></button></div></header><nav className={`nw-nav ${navOpen ? 'open' : ''}`}>{NAV.map(([group, items]) => <div key={group}><div className="nw-navgroup">{group}</div>{items.map(([id, label, num, live]) => <button key={id} className={`nw-navitem ${view === id ? 'sel' : ''}`} onClick={() => { setView(id); setNavOpen(false) }}><span className="nw-nid">{num}</span>{label}{live && <span className="nw-live">Live</span>}</button>)}</div>)}<div className="nw-nav-brand-card"><div className="nw-brand-water-icon">💧</div><div className="nw-brand-tagline"><strong>Reliable Water Data.</strong><span>Informed Decisions.</span><em>A Resilient South Africa.</em></div></div></nav><main className="nw-main">{content}</main></div></div>
}
